### ISSUE TITLE
AKMicrophoneTracker doesn't track frequency on physical iOS device

### ISSUE THREAD

**Issue by johnellmore** [AudioKit/AudioKit#1118]
When I use AKMicrophoneTracker on a physical device, the the frequency and amplitude are always both zero. But in the playground and in the iOS simulator, it works perfectly.

```swift
let tracker = AKMicrophoneTracker() // tracker is actually a property of the app delegate, so it's not being garbage collected
tracker.start()
Timer.scheduledTimer(withTimeInterval: 0.1, repeats: true, block: { _ in
    print(tracker.frequency)
    print(tracker.amplitude)
})
```

I'm using AudioKit 4.0.3.

It works as expected when using:
* the AudioKit playground on my Mac
* a simulator iPhone 7 Plus running iOS 11.1

It does not work when using:
* A physical iPhone 7 Plus running iOS 11.1.1 (and also occurs on iOS 11.1)

**Comment by aure** [comment]
Does it ask you for permission to use the microphone?

**Comment by aure** [comment]
I don't think this is a bug, maybe ask on StackOverflow so we can get some points for the solution ;)

**Comment by doriansgithub** [comment]
Hi Aure,

I'm using AK 2.0 because the code base I have for this tuner only works with 2.0 (we are trying to make it work with the latest, but that might take some time).  

It works fine as a stand alone app, but when I bring it into my app, although it doesn't crash, it doesn't listen to the mic.  I have another tuner already that works on the app, so the request for permissions shouldn't apply.

I had a "fail to output audio", then I initiated an Audio Recording Session and now I get a clean "1 MIDI sources", and MIDI source 0: Session 1", yet it's not listening.

So my question is, does AK 2.0 work with iOS 9.3 and above?

**Comment by aure** [comment]
@doriansgithub please don't use someone else's issue as a starting point for discussing your own issue. AudioKit 2 is almost 2 years and not supported.

**Comment by aure** [comment]
Reopening this issue while the StackOverflow community has a chance to weigh in: https://stackoverflow.com/questions/47401897/why-doesnt-audiokits-akmicrophonetracker-work-on-a-physical-ios-device

**Comment by aure** [comment]
I'm going to close this issue, but feel free to post here any suggested fix you'd like in AudioKit or even make a pull request.
