### ISSUE TITLE
Click on AKMorphingOscillatorBank with`AKTable(.triangle)`

### ISSUE THREAD

**Issue by carlosypunto** [AudioKit/AudioKit#1119]
Hi Aure and team, 
When holder note is played on an AKMorphingOscillatorBank with`AKTable(.triangle)` a click occurs in the loop. This happens in my own code and AnalogSynth example. `AKTable(.positiveTriangle)` is working fine, without click.

**Comment by aure** [comment]
Thanks, we are aware of this.  Stems from an issue in the table generators, @PaulBatchelor any updates?

**Comment by PaulBatchelor** [comment]
This is an issue related to how interpolation works for table lookup
oscillators. I made a hacky fix for sp_osc, but did not apply it to
sp_oscmorph yet.

**Comment by aure** [comment]
@PaulBatchelor and as you know, but just for completeness, the hack had some negative side effects so it would be cool to figure out a better overall solution if possible.  @carlosypunto you can avoid triangle for right now, in fact just a bit of smoothing or just using a sine is a pretty good solution depending on your application.

**Comment by PaulBatchelor** [comment]
@aure I *think* I may have fixed things here: https://github.com/PaulBatchelor/Soundpipe/blob/more_osc_fixes/modules/oscmorph.c#L72

I was able to get clicks using sp_osc with a triangle wave generated via sp_gen_triangled and set to be 440Hz. I was able to successfully remove those clicks with the fix I did above that did not resort to the "initial hack" (which I will explain with way too much detail below). This fix should also work for sp_oscmorph, since it is a modified version of sp_osc.

For reference, I will try to break down the bug and my various solutions here. This oscillator has been haunting me for years with bugs, so I try to leave a trail of words for my future self.

## Explanation

The reason why I believe clicks are happening in the first place is that the linear interpolation algorithm requires N+1 samples to work. That is to say, if I have 1024 sample lookup table and I am on sample 1024, it will look forward to 1025 to interpolate. The fix for this has been to have an extra sample allocated for these situations so it has something to reach for without segfaulting. Unfortunately, this value is always 0 because it never gets changed. For things line sine waves, this is fine because things start and end on 0. For things like a triangle wave where values end on -1 or 1, you get these larger skips which ends up sounding as an audible click.

## Fix 1: the "hack"

My first solution was to assume that all tables accepted into sp_osc had that extra sample, and to set it to be the first sample of the ftable. This worked fine for all my needs, but crashed on AudioKit. My only is that some tables are segfaulting because they do not have that extra sample allocated. 

## Fix 2: the modulo operation

The fix that seems to work right now is to add a modulo operation for (size - 1) samples. It sounds simple to say, but it's hard to see exactly where to put it without understanding the bit twiddling and pointer arithmetic the algorithm is doing. I'm nearly sure that is is fine, but a part of me thinks there may be some numerical side effects that I'm not factoring in.

**Comment by dkun7944** [comment]
@carlosypunto As another temporary solution, I’ve found that using the .positiveTriangle table sounds identical and has no clicks (tested on iPhone X and iPhone 6S).

**Comment by carlosypunto** [comment]
Hi @dkun7944, Thanks in any case, but temporarily I'm using that solution as I've commented above. My intention was to report the problem. It's more I'm using several AKOscillatorBank instead of just one AKMorphingOscillatorBank, I get the impression that AKMorphingOscillatorBank makes a small transition when the index of table is changed, in any case I'm doing tests to know the framework better

**Comment by aure** [comment]
This is fixed on the develop branch.
