### ISSUE TITLE
Android SDK version?

### ISSUE THREAD

**Issue by jamesharvey2** [AudioKit/AudioKit#1202]
Hello AudioKit team,

Is it possible for you guys to create Android SDK version of AudioKit? so Java & XML programmers can use AudioKit for android?

So far there are a few audio-related SDK packages for android:

http://superpowered.com/

developer.samsung.com/galaxy/professional-audio

Please be a part of this stream!

**Comment by aure** [comment]
At this point we are not interested in Android, sorry.

**Comment by jamesharvey2** [comment]
That's very unfortunate :(

**Comment by aure** [comment]
Since this was referred to in youtube comments I should clarify and update my "At this point we are not interested in Android, sorry." response.

Android is improving as a medium for music apps. And I could see other languages that could perform the swift layer functionality of AudioKit just as well (Kotlin for example).  And, as the SOUnd Language (SOUL) from Roli makes progress Android will benefit greatly.  

The "we" in AudioKit will need to change to include collaborators who have expertise in Android specific audio, but I do think AudioKit as a community will welcome implementations on Android and all other platforms.

**Comment by aehlke** [comment]
Now in 2024, I want to bring attention to a new technology that could allow for porting AudioKit to Android: Skip https://skip.tools

They've created a way to statically transform Swift and SwiftUI to Kotlin and Compose, outputting readable Android code and allowing inline `#if` pragmas to put Kotlin directly into files as needed too. Pretty incredible.

They've added support for cross-platform usage of tools like SQLite through custom open src clients. So there is potential for AudioKit or interested parties to add a Skip client for transforming AudioKit usage into Android platform code. Then all AudioKit users (either through open source or commercially I suppose) would gain Android support automatically, without having to also build and maintain a kinda-similar Android version independently.

This would also save AudioKit devs from having to learn Android thoroughly, since it already does a lot of the transformation.

I believe Android market has grown and have seen more reports of devs achieving relatively comparable paying customer numbers in some niches between Android / Apple these days, so there's a commercial case for it.

(I have no affiliation with Skip, but I talked to the founders and discovered they're using my open src SwiftUI WKWebView component)

**Comment by aehlke** [comment]
cc @aabewhite cross-platform AudioKit support for Android music apps is a niche you could target with adding support to Skip, and good for showcasing a very audio/visual use case.
