### ISSUE TITLE
AKSequencer fails when build target doesn't have the background audio mode enabled

### ISSUE THREAD

**Issue by teroparvinen** [AudioKit/AudioKit#1280]
I completed the app I was working on, and submitted it for review to Apple. They rejected because I had specified an audio background mode for the app and it didn't seem to take advantage of it. I had no issue with this because they are correct.

So I went ahead and disabled the background modes, but now all `AKSequencer`s started doing super strange things. I'm in a hurry to get things fixed, but according to my quick analysis it seems that they are ignoring all routing. I have one sequencer running a callback instrument updating the interface and another connected to a sampler. Both are playing a simple sine wave as soon as I disable background audio. No other changes.

Since my need is quite simple, I'll probably work around this by ditching all sequencers for a custom solution, but would love to hear if there's any insight into this.

**Comment by markjeschke** [comment]
Instead of ditching all of your sequencers, what if you were to add the free Audiobus 3 SDK into your app and make it Audiobus compatible? Audiobus requires background audio (that Apple will approve) and will ultimately extend the usage and visibility of your app, since Audiobus allows your app’s audio to be processed with third-party effects, or recorded into GarageBand, Loopy, or Cubasis. 

For Audiobus integration, you can check out these resources:

http://audiokit.io/audiobus/

https://github.com/AudioKit/ROMPlayer

**Comment by aure** [comment]
Mark has a pretty clever solution, I like that. If you're using sequencer to do a callback, you could also use AKTimeline I think.

**Comment by teroparvinen** [comment]
The reason background audio was initially on was because I was looking into Audiobus integration at one point. I decided against it because it was a bit too complicated at that point and wasn't exactly needed in my case. I may look into it in the future, but for now I managed to just replace the sequencers with a custom timer loop, because my needs were limited indeed.

However, this does not address this issue at all. Requiring all apps that use Audiokit's sequencers to also include Audiobus doesn't sound like a solution to me.

**Comment by markjeschke** [comment]
Since you said that you were in a hurry, it was meant as a quick solution to your background audio/Apple rejection, rather than a fix to the sequencer issue. I have no idea what is causing the “strange things” with your sequencer. A sample project would help with trouble-shooting in order to truly test and replicate the bug that you’re experiencing. 

You’re right; my comment did not address the question issue, but I was just trying to help.

**Comment by aure** [comment]
My feeling is that AKSequencer is not doing anything that is requiring background audio to be assigned except to use Apple's own sequencer stuff.  They might not realize that this is in fact their issue. I don't see how I could require background audio even if I tried. Feel free to reopen the issue with more information, but because I don't feel like I can act on it, I'll close it for now.
