### ISSUE TITLE
Audiokit.framework/Audiokit is 253mb is that okay ?

### ISSUE THREAD

**Issue by omarojo** [AudioKit/AudioKit#1300]
Previous versions of Audiokit that I compiled using the provided script were around 86mb or so.
But this one bloated into a +200mb I wonder if it is expected. At least the iOS framework is.

**Comment by megastep** [comment]
This might have to do with some changes to the way the debug information is included in this release. Supposedly you would get loads of warnings at link time otherwise.

On the plus side, since this is a static framework, even though the library itself is big, only the parts you actually use should make it inside your final compiled binary.

**Comment by megastep** [comment]
Also the reason the iOS version is much bigger than the others is because we have 5 processor slices included (i386, x86_64 for simulators, armv7, armv7s and arm64), whereas other platforms only need 2 usually.

**Comment by omarojo** [comment]
I see... so it's expected.
I just had issues with Github.. because I cant commit because file is too large haha. :(

**Comment by megastep** [comment]
We also ran into issues with the size archive for CocoaPods becoming a problem with GitHub... you really shouldn't be checking in compiled binaries in your GitHub repos though!
