### ISSUE TITLE
Large jump in AudioKit.framework filesize between cocoapods install and sourcecode build.

### ISSUE THREAD

**Issue by bmgire** [AudioKit/AudioKit#1326]
The AudioKit cocoapods install process for version 4.2.3 creates an AudioKit.framework file that's 262 mb, however, the unaltered 4.2.2 source code  generates a 48mb AudioKit.framework file. Is this large size discrepancy expected?  I only noticed this because I was unable to push my most recent branch to github due to the large file size of the framework in 4.2.3. Github does have a tool managing version control with large file sizes, but I wanted to bring this to your attention in case that large file size is not expected.

**Comment by megastep** [comment]
The biggest reasons for the file size from CocoaPods is because of: 
1) the 5 different CPU slices included (i386, x86_64, arm7, arm7s and arm64) - essentially that multiplies the size of the binary.
2) Debugging info, we had to switch to a format that's slightly fatter for static libraries
3) Bitcode - this adds a lot of extra cruft but is required by Apple

The good news is that all of it is stripped down to just what you need when you build and submit your app. This is mostly so that one single framework covers all bases.

In any case, you really shouldn't be including binaries in your Github repository. I suggest you stick to just the Podfile, which in turn will download the files straight from the source when you do a `pod install`.

**Comment by megastep** [comment]
When you build the framework yourself inside of Xcode, it will only build for the current architecture by default so it's normal for it to feel about 5x smaller just because of that.

**Comment by megastep** [comment]
So anyway this is not really an issue - don't try to bundle the binary in your repo and you should be fine. The main advantage of us switching to static libraries is that you no longer have to bundle and sign a 250MB framework within your app either, since the static linker strips it to just the parts you actually use. In turns this makes your own apps much smaller and faster to load. :)

**Comment by bmgire** [comment]
Thank you so much for the info!
