### ISSUE TITLE
Installing via CocoaPods doesn't allow you to check Pods into GitHub

### ISSUE THREAD

**Issue by khanlou** [AudioKit/AudioKit#1376]
AudioKit is working well for us, but we're having an issue with the interplay between CocoaPods and GitHub. I couldn't find this issue being tracked anywhere else, so I'm making a new one.

When you install AudioKit via CocoaPods, it installs a 149mb binary. This is bigger than GitHub's filesize limit, which causes this error:

> remote: error: File Chet/Pods/AudioKit/iOS/AudioKit.framework/AudioKit is 149.82 MB; this exceeds GitHub's file size limit of 100.00 MB

The easiest workaround for this is to ignore your Pods in git, but that causes a host of other problems and is generally discouraged by the CocoaPods team:

> Whether or not you check in your Pods folder is up to you, as workflows vary from project to project. We recommend that you keep the Pods directory under source control, and don't add it to your .gitignore. 

On another project, I had this issue with the Google Maps binary, and we ended up using git-lfs while the Google Maps team worked on the issue. That worked, but it required everyone to have git-lfs installed and it was generally painful to use. What the Google Maps team eventually did is split the library into two static libraries, each smaller than the 100mb limit.

Do we have any options here? Are there any natural fault lines on which the AudioKit binary can be split up? Are there resources in the binary that can be extracted and shared as separate files?

**Comment by megastep** [comment]
I would generally disagree with the assertion that you should check in any kind of large binary files in Git. Really you would be served just as well by simply keeping the `Podfile` and `Podfile.lock` files as references. Git is notoriously horrible at handling large binary files and you will rapidly run into all sorts of problems. LFS is the official solution to these kinds of issues, if you're OK with the other limitations that Github puts on that (such as bandwidth).

We ran into these limitations ourselves and had to move the hosting of the binaries outside of that Github too.

AudioKit is a very large library and we recently switched it to a static framework so that it wouldn't bloat app binaries so much (most people only use a tiny subset of the functionality). I'm not convinced breaking it up further would necessarily alleviate what at its root is a problem with Git and Github.

**Comment by aure** [comment]
In any event, the notion of splitting up AudioKit into smaller chunks is on our radar, but its much too big of an effort to be listed as an issue on here.  We try to keep issues actionable.

**Comment by khanlou** [comment]
@aure Totally cool with you closing this, but our team is going to have to make a move on this soon. It's a lot of cognitive load on us to download pods each time we switch branches, as well as not being able to work offline, people accidentally doing `pod update` instead of `pod install`, `git bisect` requiring a `pod install`, etc.

Do you have any recommendations on how we might set up CocoaPods to build AudioKit from source rather than relying on a pre-built static lib?

**Comment by megastep** [comment]
This would be quite a bit change from the way our pod is set up, and the main reason is because it takes a *long* time to build the library (easily 20 minutes or so). We do have scripts for that purpose, so maybe you could call these within the Podspec, or maybe simply rely on the internal xcodebuild runs if that's good enough for your purposes.

**Comment by aure** [comment]
Maybe you could consider ways to have AudioKit parallel to your project.  That's the way I do a lot of my development.  I point up a directory and down into AudioKit.
