### ISSUE TITLE
AKNodeOutputPlot stops working when app is used as sender in inter-app audio.

### ISSUE THREAD

**Issue by GrantJEmerson** [AudioKit/AudioKit#1381]
I recently added support for Audiobus and inter-app audio to my app. However, when I go to GarageBand and add my app as the instrument, although it does show up and sounds perfectly fine, the AKNodeOutputPlot view does not show any waveforms. It simply shows a flat line.

**Comment by aure** [comment]
Audiobus steals the output so you have to make the plot tap at a point earlier in the signal chain.  So, just create a fake mixer one step ahead of the output and use that as your source for the node output instead. This probably should have been asked on StackOverflow instead so that it could seen by others.

**Comment by GrantJEmerson** [comment]
Okay, thanks for the quick reply!
