### ISSUE TITLE
Is there some way for integration AudioKit with DAWs?

### ISSUE THREAD

**Issue by whereismymind7** [audiokit/AudioKit#147]
subject

**Comment by aure** [comment]
Not yet.  In theory, we should be able to create a VST/AU plugin written in AudioKit syntax, but we haven't attempted to do so yet.  Instead of posting here, you might get more eyeballs on the idea by joining the google group mailing list.  Perhaps if enough people are interested a team can be put together to make it happen sooner rather than later
