### ISSUE TITLE
AKAudioPlayer stops playing when AVQueuePlayer starts

### ISSUE THREAD

**Issue by minikin** [AudioKit/AudioKit#1475]
I have a viewController on which I use AudioKit to play audio file and EQ it.
Also, I need to play videos in that viewController.
The issue is that AKAudioPlayer stops playing when AVQueuePlayer starts.
The problem is simply reproducible on real devices (iPad).

You can find the demo project [here](https://drive.google.com/file/d/1BFnV5DTFmRTv27Njq8tQcu0npM3J25WS/view?usp=sharing).
(I embded AudioKit as a framework, can't push it to GitHub. It's too big )

Thank you in advance for the help @aure !

**Comment by minikin** [comment]
Demo project at [Dropbox](https://www.dropbox.com/s/loqhknjbsqr7lrb/Music%20Visualisation.zip?dl=0)

**Comment by aure** [comment]
Hi, I have been on travels, I will get to this asap

**Comment by aure** [comment]
Looking at this today.

**Comment by aure** [comment]
I was able to run your app on my iPad Pro, I think without issues, but maybe I'm not understanding what the app should be doing.  I updated to the latest AudioKit because I had to do so since I'm on beta operating systems, but other than that I only had to change some "pause" to "stop" and "resume" to "play".  I'll close the issue for now, but will reopen on more information.
