### ISSUE TITLE
AKPlayer (pause, isPaused) is broken

### ISSUE THREAD

**Issue by apprithm** [AudioKit/AudioKit#1566]
Here is my coded:

Button 1 call: player.pause()
Button 2 call:
if player.isPaused{     <------ this line is always false.
  player.resume
}

Confirmed it's broken on iOS v4.5.4, and it's working on iOS v4.5.3

Also, I realized AudioKit.start() take significant longer on v4.5.4 than v4.5.3

**Comment by aure** [comment]
I don't see how start up time can be affected, core files weren't changed.  What's in the signal chain?

**Comment by apprithm** [comment]
@aure I think Im wrong about startup time. 
But the isPause flag is indeed broken.

**Comment by wahidac** [comment]
also seeing this, looks like the pauseTime gets nilled out immediately after getting set by stopCompletion(). I'm also noticing that after calling pause() on an AKPlayer, it starts broadcasting a currentTime of 0 because the internal player node has been stopped (and therefore reset to t=0 in the timeline). Is that expected behavior?

**Comment by ryanfrancesconi** [comment]
I will look at this, sorry for the delay.

**Comment by killerham** [comment]
The issue is here: https://github.com/AudioKit/AudioKit/blob/78800e4b58d5cdf033ba0365194453f8ef2a14b9/AudioKit/Common/Nodes/Playback/Players/Player/AKPlayer%2BPlayback.swift#L52

**Comment by killerham** [comment]
As a temporary fix, use AKAudioPlayer. It works with pause/resume as well as looping.

**Comment by ryanfrancesconi** [comment]
Hi, there is a PR in that will fix this issue. Will have an update soon.
