### ISSUE TITLE
App Audio issue when app is in background for over an hour

### ISSUE THREAD

**Issue by fuad-adetoro** [AudioKit/AudioKit#1570]
Hey Guys, I have an app which uses AKMIDISampler & AKSequencer, I'm initialising the AKMIDISampler with a soundfont file(.sf2). In this app you can record a sequence for up to 4 seconds and play it back to yourself. The problem I'm currently facing and I've noticed it for over a month now too, is that when the app is in the background for over an hour AudioKit seems to play a sine tone instead of the sample. 

Any help or solution will be greatly appreciated, thank you.

**Comment by aure** [comment]
Hi Fuad, I'm traveling but will have a look at this when I get back.  Didn't want to leave you hanging.

**Comment by fuad-adetoro** [comment]
Hi Aure, That's fine, thankx.

**Comment by fuad-adetoro** [comment]
Hey Aure, I just wanted to know if you've been able to look into this. It's not too urgent but I'd very much like to fix the issue on my app, Thanks :).

**Comment by jumbopilot** [comment]
Hi Aurelius, I experience a similar issue likely related to the same issue/root cause.

I do use a  
```
let oscillator = AKOperationGenerator { _ in            
            let oscillator = AKOperation.fmOscillator(baseFrequency: Synth.frequency,
                                                      carrierMultiplier:
                                                      modulatingMultiplier: 0.8,
                                                      modulationIndex: 1,
                                                      amplitude: Synth.amplitude.triggeredWithEnvelope(
                                                        trigger: AKOperation.periodicTrigger(period: Synth.cyclic),
                                                        attack: 0.01,
                                                        hold: Synth.hold,
                                                        release: 0.01))
            return oscillator
        }
        return oscillator
```

and the following overwritten AKSettings:
```
        AKSettings.playbackWhileMuted = true
        AKSettings.useBluetooth = true
        AKSettings.defaultToSpeaker = true
```

Preconditions:
iOS Audio background mode is set, AudioKit v1.0, iOS12.x, Xcode 10, Swift4.2.
Now, starting and playing the required audio is all fine. I do connect an external BT device (Audiostreaming receiver) and the output is correctly routed to the BT Audio device.

Once the BT device disconnects by itself, the audio is again correctly routed to the default speaker.

Action: Lock the device and continue listening to the audio output.

Observed: For some not yet understood reason, the audio is cut after approx. 3-5 hours; may be because of some timeout process or re-initialisation (not programmatically).

While the system under test is kept unchanged, make the BT audio streaming device again available after 7-8 hours... the audio gets switched again to the BT streaming device and the oscillator output is still running stable and audible. 

So, the whole question is what happens after a while when audio route is kept unchanged for longer? Does iOS or AudioKit cause the timeout?
PS: should you have any debug procedure to follow, just let me know.

**Comment by aure** [comment]
I am on travels for a bit longer, back next week.

**Comment by fuad-adetoro** [comment]
Coolio, I'll be waiting :).

**Comment by fuad-adetoro** [comment]
@aure Any update on this?

**Comment by aure** [comment]
I think @jumbopilot's issue might be different even though the steps to reproduce also contain the one hour wait.  Thing is I don't have any idea where to look for this. We certainly haven't built in any time limits that I know of. In AudioKit 5 we're looking to have more of the session and hardware stuff based in external dependencies from AudioKit because its a very domain specific expertise that other people might be more interested in keeping on top of than I am.

**Comment by aure** [comment]
Do you think you could share a project that exemplifies/highlight the bad behavior. Its so hard to debug or fix otherwise.  I'll close for now, but feel free to reopen with more information or resources.
