### ISSUE TITLE
build ./build_frameworks.sh fails

### ISSUE THREAD

**Issue by tetrohed** [AudioKit/AudioKit#1575]
I get a bunch of these errors

/Users/arminghajarjazi/Projects/AudioKit/AudioKit/Common/Internals/AudioKitHelpers.swift:388:26: 'CategoryOptions' is not a member type of 'AVAudioSession'

my xcode shows:

iOS SDKs:
	iOS 11.3                      	-sdk iphoneos11.3

iOS Simulator SDKs:
	Simulator - iOS 11.3          	-sdk iphonesimulator11.3

macOS SDKs:
	OS X 10.9                     	-sdk macosx10.9
	macOS 10.13                   	-sdk macosx10.13

tvOS SDKs:
	tvOS 11.3                     	-sdk appletvos11.3

tvOS Simulator SDKs:
	Simulator - tvOS 11.3         	-sdk appletvsimulator11.3

watchOS SDKs:
	watchOS 4.3                   	-sdk watchos4.3

watchOS Simulator SDKs:
	Simulator - watchOS 4.3       	-sdk watchsimulator4.3

**Comment by aure** [comment]
Which version of Xcode are you using?  Build frameworks is the single most tested part of AudioKit since every time we push a change or make a pull request on Github, that is what is run to compile everything and run the unit tests.  https://travis-ci.org/AudioKit/AudioKit

**Comment by megastep** [comment]
The scripts will use the current SDK in Xcode, however because we started using some features that are only available in Swift 4.2 / Xcode 10 this probably will not work unless you actually use Xcode 10. I suggest you install Xcode 10 separately and use `xcode-select` to switch the CLI between 9 and 10.
