### ISSUE TITLE
While connecting to a bluetooth speaker, Audio playback is delayed

### ISSUE THREAD

**Issue by PrinceAbraham** [AudioKit/AudioKit#1719]
The code is as simple as this:
let mic:AKMicrophone = AKMicrophone()
AKSettings.useBluetooth = true
AudioKit.output = mic

My phone is connected to a bluetooth speaker and everything I speak through it is delayed. Why is it not realtime like "Mega mic", an application on App Store?
Considering there's no filters it should be realtime.
Also if I stretch a word, lets say "OOOOOOOO" for 6 seconds the mic goes in and out which creates a discrepancy in the sound.

My goal is to have the speaker respond as soon as I speak like this example on youtube: https://www.youtube.com/watch?v=8GvOiEPJB4g

**Comment by aure** [comment]
Audio will be delayed for any bluetooth speaker set up.  We make some drum apps, and the delay is noticeable. Even on the video you cite, I hear a delay from when she speaks and when the sound comes out of the bluetooth speaker.  Here's a display of someone testing this out: https://www.youtube.com/watch?v=sRseTquanaw. I'd rather have questions like this brought up on StackOverflow so that more people could have a chance to answer and. the discussion more easily found.  Once we know what the problem is in AudioKit, it can be turned into an issue that we can address.

**Comment by dennislysenko** [comment]
I can confirm, even if you get pro software like Logic on a mac and use airpods, there is noticeable latency around 200ms I think. it's just part of using bluetooth audio. movie playback for example introduces a delay to the video frames being shown when bluetooth is being used for audio, to compensate for the latency. in real time audio, that's just not suitable.

**Comment by PrinceAbraham** [comment]
Some latency is fine but AudioKit has major delay. If you look at an App on App Store called Mega Mic you can see that the latency is very minor compared to the latency through AudioKit. I think AudioKit could use a major optimization compared to Mega Mic's processing time.

**Comment by aure** [comment]
Then use megamic's open source framework, right?
