### ISSUE TITLE
AudioKit Recorder example crashes with EXC_BAD_ACCESS with AKNodeOutputplot, AKSlider

### ISSUE THREAD

**Issue by alexism7hz** [AudioKit/AudioKit#1770]
In the Recorder example, all lines that set the node to AKNodeOutputPlot, such as `plot?.node = mic`, throw an EXC_BAD_ACCESS error. This happens when the iOS app is opening. Moreover, the following lines create the same error in the example (AKSlider):

```
frequencySlider.callback = updateFrequency
resonanceSlider.callback = updateResonance
frequencySlider.range = 10 ... 20_000
frequencySlider.taper = 3
```

It happened when I've updated to Mojave, Xcode 10.2 and Swift 5. I installed Audiokit 4.7.1 using CocoaPods. I'm having a similar problem with an app I developed that uses AudioKit 4.2.2.

The HelloWord example does not crash and there is no code that sets the node to AKNodeOutputPlot.

Thanks!

**Comment by aure** [comment]
The relevant issue seems to be that the class is not being found.  The framework for the AudioKitUI was missing, but even after including it I get: Unknown class _TtC10AudioKitUI8AKSlider in Interface Builder file.

**Comment by aure** [comment]
I had to add an "Other Linker Flags" entry for "-all_load" so that AudioKitUI would be properly included with the project. Not sure why Xcode tries to remove it.

**Comment by megastep** [comment]
Technically that's because the linker optimizes away the classes that it thinks are not being used in the code in the final binary (not realizing they are being loaded dynamically by xib/storyboard files). So `-all_load` explicitly tell it not to do that. It's usually only a problem with UI classes because of this particular case, and because we are using static frameworks which are subject to this linker optimization.
