### ISSUE TITLE
Adding Effects To the Microphone

### ISSUE THREAD

**Issue by joeblau** [audiokit/AudioKit#178]
I'm trying to process input from the microphone, perform some effects, and play the effects back in real time.  This is the current state of my project

```swift
class ViewController: UIViewController {
    
    var microphone = Microphone()
    var stereoAmplifier: StereoAmplifier?
    var stereoAudio: AKStereoAudio = AKStereoAudio.globalParameter()

    required init(coder aDecoder: NSCoder) {
        // Create Stereo Audio
        stereoAudio.rightOutput = microphone.auxilliaryOutput
        stereoAudio.leftOutput = microphone.auxilliaryOutput
        stereoAmplifier = StereoAmplifier(audioSource: stereoAudio)
        super.init(coder: aDecoder)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        if let stereoAmp = stereoAmplifier {
            AKOrchestra.addInstrument(microphone)
            AKOrchestra.addInstrument(stereoAmp)
            microphone.start()
            stereoAmp.start()
        }
    }
}
```

I'm new to this library and I can't find any examples or figure out how to add effects to the microphone Instrument.  I tried adding a high and low pass filter, but the output was never modified.

**Comment by aure** [comment]
You're using the default instruments, which is great, but once you start modifying, you may have to work with operations, which work inside operations.   I'll explain two things here.  

First, the microphone is like any other sound source, you can send it though the other modifying instruments, in fact you are sending it to the amp.  If you want to add reverb to the sound, you would insert the the ReverbProcessor instrument in between the mic and the amp.

But, there aren't any pre-made instruments that do stuff like low and high pass filter, so you can either make a new instrument or just edit the microphone or amp instruments to include those filter in the appropriate place.  For instance, inside the microphone you might to do this:

        AKAudioInput *microphone = [[AKAudioInput alloc] init];
        AKLowPassFilter *lpf =[AKLowPassFilter filterWithInput:microphone];
        _auxilliaryOutput = [AKAudio globalParameter];
        [self assignOutput:_auxilliaryOutput to:lpf];

Notice I added the lpf and then sent the lpf to the auxilliary output.  Your end result will be a lot more complex than this sure, but this is a start.

I see you are writing in Swift, but if you are  comfortable with Objective-C too, I would recommend building a playgroun around this so you can hear the output right away.

Also, this conversation might be better for the Google group that we have set up since its not really an issue with AudioKit but more of a conversation that we can have and others can benefit by listening in.

Aure

**Comment by joeblau** [comment]
@aure Thanks for your help. This is starting to make more sense.  I just joined the google group.  And thanks for the talk at the Meetup last night :+1:

**Comment by joeblau** [comment]
I was playing around with this more a little last night and there seems to be a bug.  I tried to implement the code you suggested but I don't get any output.  I know obj-c, but I'm not sure if it works in obj-c or not as I've been primarily working in Swift.  What appears to be happening is that if i just route `AKAudioInput` to `AKStereoAudio` or `AKAudio` then everything works fine.  As soon as I try and add a `AKLowPassFilter`, the audio stops coming though my headphones.

Here is my `ViewController.swift`
```swift
import UIKit
import AudioKit

class ViewController: UIViewController {

    let microphone = MicProcessor()
    var stereoAmplifier: StereoAmplifier?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        if let stereoAmplifier = StereoAmplifier(audioSource: microphone.auxilliaryOutput) {
            AKOrchestra.addInstrument(microphone)
            AKOrchestra.addInstrument(stereoAmplifier)
            
            microphone.start()
            stereoAmplifier.start()
        }
    }
}
```

And here is my `MicProcessor.swift`
```swift
import AudioKit

class MicProcessor: AKInstrument {
    let auxilliaryOutput = AKStereoAudio.globalParameter()
    let working = false
    
    override init() {
        super.init()
        let microphone = AKAudioInput()
        let stereoInput = AKStereoAudio(leftAudio: microphone, rightAudio: microphone)
        
        if working {
            // This codepath works and I can hear the audio coming from
            // AKAudioInput -> AKStereoAudio
            appendOutput(auxilliaryOutput, withInput: stereoInput)
        } else {
            
            // This codepath fails and there is no sound coming from
            // AKAudioInput -> AKLowPassFilter -/-> AKStereoAudio
            let lpf = AKLowPassFilter(audioSource: stereoInput)
            appendOutput(auxilliaryOutput, withInput: lpf)
        }
    }
}
```

Here is my sample project so you can see if it's working for you. https://github.com/joeblau/Silencer

I was however able to get effects to work with other instruments that were not the `AKAudioInput` or `Microphone`

**Comment by aure** [comment]
Be careful not mix up AKStereoAudio and AKAudio.  Since the microphone is a mono instrument, I wouldn't make its output stereo, but since you did, just replace the else block with this:

            let lpf = AKLowPassFilter(audioSource: microphone)
            let stereoLPF = AKStereoAudio(leftAudio: lpf, rightAudio: lpf)
            appendOutput(auxilliaryOutput, withInput: stereoLPF)
