### ISSUE TITLE
support for Mac catalyst 13+

### ISSUE THREAD

**Issue by ghubaddole** [AudioKit/AudioKit#1802]
Code built for ios using AudioKit (using 4.8.b1) works great.
But when built for mac (on xcode 11 beta 3), compilation fails with 
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/GLKit.framework/Headers/GLKit.h:11:9: 'GLKit/GLKView.h' file not found
from /Pods/AudioKit/iOS/AudioKitUI.framework/Headers/EZAudioPlotGL.h:26:9: Could not build module 'GLKit'

**Comment by megastep** [comment]
Odd, I wonder what might be broken here as I don't think GLKit has been obsoleted in Catalina...

**Comment by megastep** [comment]
Actually it looks like `GLKView` itself has been deprecated, so that might be why: https://developer.apple.com/documentation/glkit/glkview

**Comment by ghubaddole** [comment]
This is coming from EZAudioPlotGL. there's EZAudioPlot that shouldn't be using GLKView...

I wonder if it's possible (at least in the short term) to conditionally compile that file on ios 12 and below? (perhaps in the next 4.8.b2?)
Because, Audiokit is already designed to work on macos -- which is truly phenomenal -- i can just compile for the mac using catalyst and in theory it should just work - truly an amazing prospect!

**Comment by megastep** [comment]
Yes we'll definitely look at that but I anticipate some significant structural changes in AudioKit for Mac since we'd have to support a whole new `UIKitforMac` target platform in addition to AppKit.

**Comment by ghubaddole** [comment]
Ah ok!

**Comment by marcosgriselli** [comment]
Is there anything we can do to help adding `macCatalyst` support? I'm no AudioKit expert but there might be some simple tasks where a hand is needed.

**Comment by aure** [comment]
This looks like its just an issue with AudioKitUI support in Catalyst.  What I don't get is there already exists an AudioKit and AudioKitUI for Mac. Can't you just use that in your Catalyst app. Just use Catalyst for the UIKit components of your project, but use AudioKit for macOS elsewhere?

**Comment by marcosgriselli** [comment]
Yes I think the original issue is not referring to Catalyst but to the deprecated `GLKView` on AudioKit for Mac but it was the only issue mentioning Catalyst support. I've been trying to make AudioKit work with Catalyst but without success. 

Frameworks compiled for macOS or iOS won't work on macCatalyst 

|  |  |
| ------------- | ------------- |
| iOS framework  | <img width="606" alt="Screen Shot 2019-08-03 at 19 35 04" src="https://user-images.githubusercontent.com/14804033/62430888-d39df580-b6f8-11e9-84f3-7e2152a713fe.png">  |
| macOS framework  | <img width="605" alt="Screen Shot 2019-08-03 at 19 36 53" src="https://user-images.githubusercontent.com/14804033/62430889-d39df580-b6f8-11e9-8fdf-29ba0c8f7758.png">  |

I guess the `xcodebuild` command that generates the frameworks on `build_frameworks.sh` will have to add the new `macCatalyst` target. 

But I also found issues when adding AudioKit from source to a demo project (2 compile issues but I commented them out for now). Adding AudioKit for iOS compiled and run only to crash on `try! AudioKit.start()` due to not finding input nodes. 

<img width="742" alt="Screen Shot 2019-08-04 at 20 34 52" src="https://user-images.githubusercontent.com/14804033/62430995-f250bc00-b6f9-11e9-8798-a74a307dd3f8.png">

I wasn't successful in compiling AudioKit for Mac from source in this demo project. And the errors were not helpful at all: `Command Ld failed with a nonzero exit code`. 

I might be missing something obvious in order to ran a macOS framework with Catalyst since it makes sense that macOS frameworks ran out of the box. Anyway I'll be looking into the whole Catalyst iOS/macOS frameworks mechanics this week so I'll keep the issue updated with my findings.

**Comment by aure** [comment]
According to @sieren after the latest commits to AudioKit, removing EZAudioPlotGL, AudioKit itself works on Catalyst. Many things that are common on iOS like Audiobus for instance, must also be gutted out of your app, so its not trivial, but its no longer the framework that should hold you up. Also, Cocoapods does not have support for Catalyst, so you'll need to build AudioKit for yourself. If/when Cocoapods adds support for Catalyst, please make another issue to make sure we do what we need to do on our end to work as a Cocoapod. For now, though, I am closing the issue.
