### ISSUE TITLE
AKAudioFile init Fail

### ISSUE THREAD

**Issue by Girlsmile** [AudioKit/AudioKit#1833]
i got error like that 
Error Domain=com.apple.coreaudio.avfaudio Code=1954115647 "(null)" UserInfo={failed call=ExtAudioFileOpenURL((CFURLRef)fileURL, &_extAudioFile)} 

when i was init an audioFile "self.audioFile = try AKAudioFile(forReading: url)"
url = file:///var/mobile/Media/DCIM/106APPLE/IMG_6837.MOV

is this is the format problem or others, thanks

**Comment by luohuaDev** [comment]
I got this error, too. How to fix this? Thanks

**Comment by trevor-sonic** [comment]
This is an old query but I'd like to help out, I had the same problem when I tried the same working code (on the simulator) on the device. The problem is happening somehow when the URL is not correct. Url variable is not ```nil``` but not correct. Check if you append a folder by adding ```isDirectory = true```
like:  ```url.appendingPathComponent(songsFolderName, isDirectory: true)```
So it is not about akfile. 
I hope this helps to others.
