### ISSUE TITLE
AKTimePitch latency?

### ISSUE THREAD

**Issue by lucianoiam** [AudioKit/AudioKit#1894]
I could not find an answer for this on Slack or SO. Maybe this is by design and/or my limited understanding of how time stretching algorithms work...

I have an `AKPlayer` wrapped into a `AKTimePitch` like this:

```
        let player = AKPlayer()
        player.isLooping = true
        let timePitch = AKTimePitch(player)
        timePitch.rate = 1.0
```

There is a constant latency at `AKTimePitch` output compared to the "unwrapped" `AKPlayer`. I measured ~75ms and it does not depend on hardware (tested with a 2018 iPad running iOS 13 and an old 2013 iPhone running iOS 10 with same results). I managed to get a looping `AKPlayer` sync to an Ableton Link session and everything sounds as expected with sample level accuracy, until I throw the `AKTimePitch` in. Then I have to adjust for latency if I want to keep they player in phase to the session clock, even with `rate` set to 1.0 .

W̶h̶a̶t̶ ̶i̶s̶ ̶t̶h̶e̶ ̶e̶x̶p̶l̶a̶n̶a̶t̶i̶o̶n̶?̶

Is this expected?  <-- better question

**Comment by aure** [comment]
AKTimePitch is a thin wrapper around AVAudioUnitTimePitch which is closed source, so I can't speak to the details involved there. Your best bet is to do what you've done and test the unit and learn from its performance rather than its implementation details which unfortunately we do not have access to.  I will see that because this node does not work on real time signals, I would have expected it to have very low latency. 🤷‍♂

**Comment by lucianoiam** [comment]
That was a helpful clue, thanks!
