### ISSUE TITLE
Please provide a new version that compiled with Swift version 5.1.2

### ISSUE THREAD

**Issue by tuanback** [AudioKit/AudioKit#1910]
I've just updated to new XCode version. Now I can't build the project.
Can you please help to compile a new version to solve this problem? 
Thanks in advance.

![Screen Shot 2019-11-01 at 9 39 36 AM](https://user-images.githubusercontent.com/13817148/67994988-8dbae400-fc8b-11e9-8394-d7ae8f5f76f2.png)

**Comment by mglodack** [comment]
@tuanback I'd recommend keeping your previous XCode version and always installing the latest XCode version separately before upgrading via the Mac OS App Store. You can have multiple XCode apps installed and when you do that just be sure to update your XCode path using `sudo xcode-select -s <path to app>`. 

This approach has been a lot easier on me the developer because I can guarantee my dependencies including AudioKit work on the next version of XCode before upgrading.

**Comment by tuanback** [comment]
@mglodack Thank you for your suggestion. Since the XCode sometimes has bugs also (in XCode 11.2, there is one bug about UITextView that make apps crash), it is important to keep one stable Xcode version before upgrade to the latest version.
