### ISSUE TITLE
Feature Request: Automatic route-change handling during AKSequencer playback

### ISSUE THREAD

**Issue by btfranklin** [AudioKit/AudioKit#1968]
During playback of tracks with the new `AKSequencer`, if I cause a route change (such as plugging in an external set of speakers via USB, or plugging in headphones) the audio simply stops. When the `AKSequencer` is actively "playing", it would probably make the most sense to have it handle the route change smoothly, as the desired behavior would almost certainly be for the playback to continue uninterrupted on the new route. This would make life easier for those us using the `AKSequencer`!

**Comment by aure** [comment]
Touchy subject because we don't really want to automatically have AudioKit guess how to handle stuff. I could see route change handling for the sequencer being one way on one app and a completely different way in another. In fact, I'd like to remove the hardware aspects of AudioKit and have it be a bit distinct, kind of like how UI stuff is in AudioKitUI. I'm going to close the issue, because its nothing we can really act on, but its good that you got in touch, and you can comment on my response and we can communicate this way. If there is any specific way you think would be good to do this, then you might convince me to do something. (Or ideally if you could make. a pull request with the implementation that of course would be amazing.)

**Comment by btfranklin** [comment]
Okay, it does make sense to not have AudioKit try to make assumptions about how to handle things. However, it still doesn't seem quite right to have the playback simply stop, which is the current behavior. It seems that at least one other person has run into this issue, since I came across this question on StackOverflow (which has no answer yet):

https://stackoverflow.com/questions/57043636/is-it-possible-to-maintain-playback-in-audiokit-after-a-route-change

I think the ideal outcome would be to have the playback continue to _some_ location even with a route change, since that's desired behavior in 99% of cases. Now, the question of which route it should continue on, that's definitely more sensitive. I think in the small number of cases where it is desired that playback should stop on a route change, the developer can easily implement that, but it is hard to "undo" an undesired stop.

I would love to create a PR to help with this, but I am not at nearly a sophisticated enough level of understanding of AudioKit's internals to feel comfortable doing that.
