### ISSUE TITLE
CI builds compile files 4x

### ISSUE THREAD

**Issue by wtholliday** [AudioKit/AudioKit#2168]
Searching CI logs for "Compiling [Filename].mm" reveals it compiled 4x:

<img width="742" alt="image" src="https://user-images.githubusercontent.com/841144/87821560-e1bf2600-c824-11ea-8e9b-c5edc631e6a8.png">

If we can fix this the CI builds will run approx 4x faster and might not ever time out.

**Comment by megastep** [comment]
I think this is normal though; except for macOS, we are building for both device (arm64 and armv7) and simulator (x86_64 and i386 still) builds. We do need simulator to be included so that people can work on their projects.

In a typical Xcode build on your Mac it would only build for the current architecture but I think I'd rather catch something going wrong on any of the architectures we build for.

**Comment by wtholliday** [comment]
For the tests at least, there's no point in building for an architecture unless the tests are running on that architecture.

**Comment by megastep** [comment]
Well the reason it's happening this way is because that's doing more than CI, but actually building fully functional frameworks ready for release. The only thing regular CI builds don't do right now is upload the archives.

What we could do though is trim down the architectures that get built for regular CI builds (i.e. not for tags). I think that's the way it was on Travis (and why builds still complete on v4), but since Github Actions is capable to run everything in parallel I figured I'd rather have everything happen for now.

**Comment by megastep** [comment]
One side effect of building everything is that one can supposedly download fully built XCFrameworks from the build artifacts of any commit. Not sure anybody is taking advantage of that though.

**Comment by wtholliday** [comment]
Ok well it seems like these builds might as well run tests:

<img width="575" alt="image" src="https://user-images.githubusercontent.com/841144/87835320-a7b04d00-c841-11ea-84e5-7344c2a5dc1a.png">

**Comment by megastep** [comment]
I changed the build scripts to be more in line to what we were doing with Travis and build/test time is now around 22 minutes or so, skipping the device builds.

**Comment by aure** [comment]
Yeah, its strange, the build times have been ranging from 26 minutes to over an hour so its difficult to gauge that 22 minute time after your commit. Right after that my next commit took 26 minutes again. Hopefully that's a high water mark now.  Looks like the macOS build is taking the longest at around 11 minutes.

**Comment by megastep** [comment]
Yeah I'm not sure if I can shorten that one too somehow. Maybe skip i386.

**Comment by megastep** [comment]
Actually, the reason it takes longer on iOS is because we're building both macOS and Catalyst libraries - they are separate builds so that in effects doubles the time there. Also makes the macOS archives quite bigger.

**Comment by aure** [comment]
This seems like it might be good enough now. If not, please feel free to reopen the issue.
