### ISSUE TITLE
iOS 14 mic privacy indicator

### ISSUE THREAD

**Issue by jamiehunt** [AudioKit/AudioKit#2291]
Posting new issue since I cannot re-open issues, but this is basically the same as: https://github.com/AudioKit/AudioKit/issues/2273

Here I attach an example project using the V5 branch: https://github.com/jamiehunt/AudioKitSandbox/tree/master/AudioKitSandbox

In my example engine is initialised without the mic being attached - privacy indicator off (as expected)
We can play clips and do 'listen only' things without triggering the indicator (as expected)
We can use the input node, create a fader with gain 0 to attach to output, and begin using SFSpeechRecognition. Indicator enables (as expected)
Then we detach mic and restart the audio session, fails to start with:
"Domain=com.apple.coreaudio.avfaudio Code=-10868 "(null)" UserInfo={failed call=err = AUGraphParser::InitializeActiveNodesInInputChain(ThisGraph, *GetInputNode())}". And since audio session is not running no mic indicator
Now we try and play an audio clip again, audio starts, successfully this time, but still has a handle on the input node so privacy indicator is active (unexpected)

So reproduction flow is: Starting with speech recognition permissions, play sfx, play sfx, recognize speech, play sfx

What is the recommended approach for disabling microphone after use, whilst continuing with an audio session?

Many thanks.

**Comment by warpling** [comment]
AFAIK It's not possible to maintain an engine that has had its inputNode instantiated by being referenced. Sadly iOS doesn't differentiate reading buffers from the inputNode from having an inputNode so just having it exist to a running engine will trigger the privacy indicator. I _think_ you can stop the engine, tear it down and use a new engine to get rid of the dot …but I would probably just try to migrate to v5 as it becomes available because it makes it much easier to make multiple parallel engines you can easily bring up and destroy as needed!

**Comment by jamiehunt** [comment]
@warpling  Ah, this is great, I wasn't aware it's possible / advisable to be using multiple engines. Cool, implemented as you suggest and working great. Thanks for the direction!
