### ISSUE TITLE
Mixer.volume Has No Effect

### ISSUE THREAD

**Issue by jsl303** [AudioKit/AudioKit#2372]
I'm using AudioKit v5-main.
It used to work in v4, but the volume stays the same regardless I set at 1.0 or 0.0.
Am I missing an api change, or is this a bug?

```
let Mixer = Mixer(osc)
mixer.volume = 0.5
```

Thanks!

**Comment by aure** [comment]
I've verified that it doesn't work for me either.  When you say it used to work in v4, do you mean to say that it still works in v4, or just the last time you tried it worked. The reason I ask is because the mixer's volume is being properly set down to the AU level, so it makes me think something is wrong on Apple's side. I compare AKMixer (v4) to Mixer (v5) and the way they both deal with volume is identical. Mysterious.

**Comment by jsl303** [comment]
Sorry, I meant it worked last time when I tried with v4 on Big Sur Beta.

I'm not sure if v4 still works with Big Sur 11.1.

**Comment by aure** [comment]
I just verified that the problem doesn't happen outside of AudioKit, so its not Apple's fault.

**Comment by aure** [comment]
Okay the issue is that you can't set the volume until after the mixer is connected to the engine. In AudioKit 4, this happened right away because we had a singleton engine. Now, the connections are made dynamically as needed, but it does mean you'll have to set mixer volume after you start the instance of AudioEngine. I'm not sure there's any non hacky way around this.
