### ISSUE TITLE
Ability to monitor a specific audio input on a multi-channel input device

### ISSUE THREAD

**Issue by Daniel-Higgott** [AudioKit/AudioKit#2440]
Hello,

I would like to be able to monitor a specific audio input on a multi-channel input device. As far as I can see, AudioKit allows me to monitor a specific audio input device, but doesn't allow me to specify which audio input to monitor. Whilst this is adequate for a mono or stereo device, many use-cases involve multi-channel devices.

Would it be possible to add an inputs array to a Device, so that the input could be selected, and not just the device?

@ryanfrancesconi - Would you be able to provide any pointers on this?

Many thanks in advance,

Dan

**Comment by ryanfrancesconi** [comment]
Yes, the current way AudioKit is accessing the inputNode of the AVAudioEngine doesn't support this. You need to access the inputNode directly with your tap rather than tapping an intermediary Mixer which is what AudioKit is doing.

The format that is coming from the AVAudioEngine.inputNode will represent the hardware layer's channelLayout. This means that your inputNode (in the case of real hardware) would contain something like 32 channels. This means that you have an incoming "recordFormat" of multichannel data and depending on how you want to handle that, you must separate those channels. In order to do what you want you take this multi channel format and use channel mapping. This is a Core Audio thing. To give you an idea how this works:

```
    /**
     This property is used to map input channels from an input (source) to a destination.
     The number of channels represented in the channel map is the number of channels of the destination. The channel map entries
     contain a channel number of the source that should be mapped to that destination channel. If -1 is specified, then that
     destination channel will not contain any channel from the source (so it will be silent)
      */
    private var _channelMap: [Int32] = []
    private var channelMap: [Int32] {
        get { _channelMap }
        set {
            guard newValue != _channelMap else { return }

            Log.debug("Attempting to update channelMap to", newValue)

            guard let audioUnit = inputNode?.audioUnit else {
                Log.error("inputNode.audioUnit is nil")
                return
            }
            let channelMapSize = UInt32(MemoryLayout<Int32>.size * newValue.count)

            // 1 is the 'input' element, 0 is output
            let inputElement: AudioUnitElement = 1

            let err = AudioUnitSetProperty(audioUnit,
                                           kAudioOutputUnitProperty_ChannelMap,
                                           kAudioUnitScope_Output,
                                           inputElement,
                                           newValue,
                                           channelMapSize)

            guard err == noErr else {
                Log.error("Failed setting channel map")
                return
            }

            _channelMap = newValue

            Log.debug("Updated channelMap to", _channelMap)
            recordFormat = createRecordFormat(channelMap: newValue)
            recordEnabled = false
        }
    }
```

At this point, if you recorded that format you'd be left with a multichannel CAF file, which in itself is quite useful.

But, that's not what you want. You want the channel data directly. So, for this you separate out the channels in the tap block that is received from the inputNode into mono buffers.

I have a class I will add in called `MultiChannelInputNodeTap` that does all these things for you.

**Comment by aure** [comment]
Thanks Ryan!

**Comment by Daniel-Higgott** [comment]
Thanks so much Ryan, that is so helpful of you. I'll have a look into this over the next few days, and hopefully I'll be able to get something working.

Many thanks again,

Dan

**Comment by Daniel-Higgott** [comment]
Hi @ryanfrancesconi,

Thanks again for the MultiChannelInputNodeTap class. I have been working on this today. So far in my testing I have initialised an AVAudioEngine instance using:

`let audioEngine = AVAudioEngine()`

I have then discovered the DeviceID of the physical device, and assigned it to the Audio Unit of the AVAudioEngine Input Node, like so:

`if let audioUnit = audioEngine.inputNode.audioUnit {
                let err = AudioUnitSetProperty(audioUnit,
                                               kAudioOutputUnitProperty_CurrentDevice,
                                               kAudioUnitScope_Global,
                                               0,
                                               &deviceID,
                                               size)
                
                guard err == noErr else {
                    Log("Failed setting Input Node Audio Unit")
                    return
                }
        }`

I am then initiating an instance of the MultiChannelInputNodeTap, assigning the delegate, creating a channel map and attempting to record, like so:

`tap = MultiChannelInputNodeTap(inputNode: audioEngine.inputNode)
        tap?.delegate = self
        
        let inFormat = audioEngine.inputNode.inputFormat(forBus: 0)
        var channelMap:[Int32] = [Int32]()
        for _ in 1 ... inFormat.channelCount {
            channelMap.append(-1)
        }
        channelMap[0] = 1
        tap?.prepare(channelMap: channelMap)
        tap?.record()`

The delegate is receiving a callback that the tap is installed, but never receiving any dataProcessed callbacks. I am also getting an error that the file format is nil. I'm pretty sure I am not setting up the tap correctly. Would you be able to point me in the right direction?

Many thanks again,

Dan

**Comment by ryanfrancesconi** [comment]
No, that's wrong. Sorry, I don't really have time to explain how to use AVAudioEngine, but there is info online.
Ryan

**Comment by ryanfrancesconi** [comment]
The rules are totally different when you access the inputNode of the Audio Engine. You need to let it control the internal aggregate device and you want to use a framework such as AMCoreAudio to handle your devices rather than how it is being done in AudioKit. Use the system default devices and stay in sync with what is selected in Audio MIDI Setup.
