### ISSUE TITLE
v5-main - SwiftUI app crashes when removing MidiListener

### ISSUE THREAD

**Issue by txbrown** [AudioKit/AudioKit#2451]
**Confirm you should be adding the bug here**
Hey I have found this [issue on stackoverfow](https://stackoverflow.com/questions/66307609/audiokit-v5-main-crash-when-removing-midi-listener) same as mine but no answer for a couple of months.

**Describe the bug**

App crashes with `Thread 1: EXC_BAD_ACCESS (code=2, address=0x7ffedfcc4ff8)` when removing a `MIDIListener`.

**To Reproduce**
I have a a MidiManager class like so:
```swift
  class MidiManager: ObservableObject, MIDIListener { 
      var midi: MIDI = MIDI.sharedInstance
      // some other properties...
  }
```

and a view like so:

```swift
struct HomeView: View, MIDIListener {
    // conforming methods of MIDIListener protocol
    
    var body: some View {
        VStack {
            
        }.onAppear(){
            MidiManager.shared.midi.addListener(self)
        }
        .onDisappear(){
            MidiManager.shared.midi.addListener(self)
        }
    }
}
```

Not detailed here for brevity but inside the HomeView there is a card that when tapped causes a navigation and then `onDisappear` lifecycle event is called. The app then crashes at this stage.

One workaround I found that seems silly - but I could be wrong - was to navigate and then on the other view `onAppear` event clear all the previous listeners. This seems wrong to me.

Either way I can't see why removing the MIDIListener onDisappear causes a crash.
**Expected behavior**
It does not crash

**Details (please complete the following information):**
 - Type: Mac
 - OS: macOS 11.3 Beta (20E5210c)
 - AudioKit Version  v5-main

**Additional context**

**Comment by aure** [comment]
Hi there,

So, there's a lot to tell here. First of all, I think its a bad idea to tie AudioKit stuff to the UI View life cycle, but what you're trying to do is even worse because you're adding a listener to a SwiftUI View which is not so much a View as a struct whose body is called whenever a UI View needs to be built to draw on the screen.  Its not guaranteed to have a life at all except for the time it takes to draw on the screen. So, when you are calling the closure, the self is long gone and you'll get that bad access error. 

If that doesn't make sense, let me know and I can explain more. SwiftUI is new to everyone and it has some familiar terminology but is very different from UIKit. But like I said, any UI life cycle is a dangerous thing to tie AudioKit stuff too because you can't really be guaranteed to know how or when things might be called by iOS for a variety of reasons.  I've been reading the Thinking In SwiftUI book by the objc.io guys, and I recommend it if you want a really in depth understanding of how SwiftUI really works under the hood.

Aure

**Comment by txbrown** [comment]
@aure many thanks for reply. I knew something felt odd. My first approach was with an example of a MidiConductor you have referenced before but for my specific case I was getting conflicts between different views using this shared listener (probably a different issue with my design) and went with this approach of having a listener on each view.

Anyway, thanks for the reply and book recommendation, that is also helpful to figure out a better path here.

**Comment by txbrown** [comment]
@aure is it possible to have access to the slack group please? I am building https://midicircuit.com with audiokit and this would be super beneficial to me.

Cheers 🙂

**Comment by aure** [comment]
Of course, send me an email so I can add you. Or paste in your email address here and I'll delete it right away.

**Comment by txbrown** [comment]
ricardo@yonkolevel.com 
not same as my GitHub one

**Comment by aure** [comment]
Got the email. Just use your full name when signing into the slack group. I enforce non-anonymity to foster respectful conversation there.
