### ISSUE TITLE
Updated podspec for 2.2 is not in cocoapods/Specs

### ISSUE THREAD

**Issue by ruurd** [audiokit/AudioKit#246]
Updated podspec for 2.2 is not in cocoapods/Specs. The latest there is 2.1.1

**Comment by aure** [comment]
Yeah, can't get it pass validation, but apparently it works with instructions on http://audiokit.io/downloads/

**Comment by aure** [comment]
We'll try again with 2.3 which shouldn't be too long now.

**Comment by ruurd** [comment]
Hmmm not nice. I was rummaging around with TuningFork on OS X which uses Audiokit and if I do that with 1.1.2 it points to CsoundLib.framework in /System/Library/Frameworks which does not exist on OS X 10.11.1 (which is what I am using currently...)

Can yoy tell me what you did to get it validated?

**Comment by ruurd** [comment]
OK at least weird:

$ pod spec lint

 -> AudioKit (2.2)

Analyzed 1 podspec.

AudioKit.podspec.json passed validation.

**Comment by aure** [comment]
Weird, maybe you can push it up to cocoapods?  Here's what I get when I run the same command:

└─➤ pod spec lint --verbose

    AudioKit (2.2) - Analyzing on OS X 10.10 platform.
  Preparing

Analyzing dependencies

Fetching external sources
-> Fetching podspec for `AudioKit` from `/Users/aure/Developer/AudioKit/AudioKit.podspec.json`

Resolving dependencies of

Comparing resolved specification to the sandbox manifest
  A AudioKit

Downloading dependencies

-> Installing AudioKit (2.2)
  > Copying AudioKit from `/Users/aure/Library/Caches/CocoaPods/Pods/External/AudioKit/578da0c403938689e0fd15fd64a52256-35653` to `../../../../private/var/folders/5d/zkr3lw7x71vd60mckbvrnm_w0000gn/T/CocoaPods/Lint/Pods/AudioKit`
  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
 -> AudioKit (2.2)
    - ERROR | [OSX] Encountered an unknown error (No such file or directory @ realpath_rec - /private/var/folders/5d/zkr3lw7x71vd60mckbvrnm_w0000gn/T/CocoaPods/Lint/Pods/AudioKit/AudioKit/Platforms/OSX/CsoundLib.framework/Headers) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.

/Users/aure/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/command/spec/lint.rb:72:in `run'
/Users/aure/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/aure/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Users/aure/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/Users/aure/.rbenv/versions/2.1.2/bin/pod:23:in `load'

**Comment by ruurd** [comment]
** BUILD SUCCEEDED **

2015-10-25 19:01:38 +0000 Plugin Console Open With Application: [NSApp mainMenu] returned nil
 -> AudioKit (2.2)

Analyzed 1 podspec.

AudioKit.podspec.json passed validation.

**Comment by ruurd** [comment]
But I'm not sure if I can push the podspec because I did not claim the audiokit as my own. If correct you have done that. This way they prevent all sorts of rogue podspec problems...

**Comment by ruurd** [comment]
ruurd:mctiny ~/Projects/ruurd/experiments/osx/Audiokit  [master]
$ xcodebuild -version
Xcode 7.1
Build version 7B91b

And the latest OS X...

**Comment by megastep** [comment]
Interesting, it does pass validation with the latest cocoa pods on my system. I guess they must have fixed that bug that was preventing it from working weeks ago.

**Comment by ruurd** [comment]
OK then push the podspec please then I can go and see if I can get TuningFork to work. But anyway. A well spent Sunday for me.

**Comment by aure** [comment]
I just pushed it up. Only a few months late!

**Comment by ruurd** [comment]
\0/ \0/ who cares! You did it did you? :-) Good show guys&gals.

**Comment by aure** [comment]
Appears so... https://cocoapods.org/pods/AudioKit
