### ISSUE TITLE
Sequencer not triggering note off at the end of the loop

### ISSUE THREAD

**Issue by Truba** [AudioKit/AudioKit#2536]
Hi guys,
Sry for not opening in the stack overflow first, but I'm pretty sure something is wrong here.

**Describe the bug / Expected behavior**

Sequencer doesn't seem to be triggering note off events if the note off event is placed at the end of the track loop.
Here we have an example with just that:
```swift
let sequencer = Sequencer()
let track = sequencer.addTrack(for: sampler)
track.loopEnabled = true
track.length = 4
track.sequence.add(noteNumber: someNote, position: 3, duration: 1)
```
I'm creating a sequencer that outputs to sampler, and I'm also adding just one note. I'm expecting this one note to trigger 2 events.
Note On at position 3 and note Off at position 4.
But only the note On at position 3 is triggered, note Off at position 4 is missing. 

**To Reproduce is Cookbook**

I can also replicate is by slightly modifying the Shaker example in Cookbook:
https://gist.github.com/Truba/d36ee294817446aac082d929cf3adb7d

I've updated both tracks to use longer duration, and I've updated `CallbackInstrument` to print the on/off state as well.
In the print you can see that Off event is missing for beat at position 3.

**Where the issue might lie**

 I'm pretty sure the issue lies somewhere around here:
https://github.com/AudioKit/AudioKit/blob/4c3f5ef1b7d758609c7cfbc2d1f631fc45da04d1/Sources/CAudioKitEX/Sequencing/SequencerEngine.mm#L178

I've tried tinkering with it a bit, but without success.
This was my idea, it seems to work for the first loop, but it doesn't work for any consecutive loops.
```cpp
int time = (triggerTime >= lengthInSamples()) ? triggerTime - lengthInSamples() : triggerTime;
if (time < samplesOfBufferForNewLoop) {
      int offset = (int)time + loopRestartInBuffer;
```

**Details (please complete the following information):**
 - Type: iPhone 12 Pro, iPad Pro 9.7
 - OS: iOS 14.5
 - AudioKit Version 5.2

**Comment by MathieuLescure** [comment]
I think there is still an issue. Now the last noteOff is well sent, but after the noteOn of the first beat. As a consequence, if the last and first notes are the same, a noteOff event arrives just after a noteOn for the same note, and no sound is played by the sampler. I tried to fix the issue but without success. As a workaround I just reduced very slightly the duration of the last note for it to end just before the end of the last beat.

**Comment by fvolchyok** [comment]
I experience the same issue here, both 
1.  described by @Truba when last not off is not triggered (if `sequencer.loopEnabled = false` and using default midi sampler without soundfont (aka sinewave sampler)
2. descibed by @MathieuLescure when first note is 
    a. not audible at all for sinewave sampler or
    b. barely audible for a fraction of second if used with piano sampler (which I guess confirms assumption by @MathieuLescure). 
Proposed solution to slightly shorten the last note works, but is still suboptimal and requires to takes this "fix" into consideration when producing midi files.

If it helps in any way this is an example of what I'm doing:
```
class Test4 {
    let audioEngine = AudioEngine()
    let sampler = MIDISampler(name: "melodySampler")
    let sequencer: Sequencer
    let mixer = Mixer()
    
    init() {
        // uncomment for piano sampler
        //try! sampler.loadSoundFont("YDP-GrandPiano-20160804", preset: 0, bank: 0)
        mixer.addInput(sampler)
        sequencer = Sequencer(fromURL: URL(fileURLWithPath: Bundle.main.path(forResource: "test14_last_note", ofType: "mid")!), targetNodes: [sampler, sampler])
        
        // uncomment for hanging last note
        //sequencer.loopEnabled = false
        print(sequencer.tracks[0].sequence)
        audioEngine.output = mixer
    }
    
    func start() {
        try! audioEngine.start()
        sequencer.playFromStart()
    }
}
```
where piano sampler could be taken here https://freepats.zenvoid.org/Piano/acoustic-grand-piano.html
[midi files under test](https://github.com/AudioKit/AudioKit/files/7815001/Archive.zip): test13.mid skips first note, test14_last_note.mid does not

**Comment by eljeff** [comment]
Late to the game here, but this is a cool issue cause it's literally an edge-case.

Simplest solution for all of these issues is to adjust your note lengths - I've just gotten used to it dealing with weird issues like this for years in all types of sequencers (especially when looping is involved).

I think of it like an array, you can have 10 items but you can't access array[10] because thats out of bounds. If your sequence is 4 beats long, the beginning of the 4th beat could be considered out of bounds.

It gets kind of complicated .... should it play both position 4 of the outgoing loop and position 0 of the incoming loop? What if there is another noteOn at downbeat 4.0 and you are trying to loop a subsection of 0-4.0? That new note will hang now.... so its almost like you need to treat noteOn and noteOffs differently (there's precedence for this, but that adds more complexity).

If there's an elegant fix, I'm all for it, but if the fix causes new issues, I think it might be a good idea to keep the code simpler and let the user adjust notes accordingly so the math just shakes out.

I've fixed a similar issue a while back with repeated notes, one ending exactly where the old one stopped - not sure if that code is still around or not, but it matters which order you process the noteOn vs noteOff.

**Comment by emurray2** [comment]
Closing this and reopening in AudioKit/AudioKitEX to help keep track of issues related to AudioKitEX

**Comment by derekleerock** [comment]
Since I came by this and wanted to see the status/progress of the issue, here's a link for anyone else who happens by: https://github.com/AudioKit/AudioKitEX/issues/12
