### ISSUE TITLE
How to prevent default microphone permission on audikit start?

### ISSUE THREAD

**Issue by Mustafax06** [AudioKit/AudioKit#2712]
I've seen [this issue](https://github.com/AudioKit/AudioKit/issues/668) and I tried this and it doesn't work for me and there are plenty of unanswered questions about this issue on StackOverflow. Is there a way to prevent this native popup? I want to add the version I'm using, but I couldn't find it because AudioKit is directly embedded in my project. My iOS app supports iOS 13 and above devices.

**Comment by emurray2** [comment]
Unfortunately, no. The only way to prevent it is by not accessing the microphone at all.

This popup isn't something controlled by AudioKit. In fact, you can always get it to show up with one line of code `AVAudioEngine().inputNode`.

The popup is required by Apple whenever you access this node because they assume you're using it to record. Thus, the user always has to be informed the moment it's accessed due to privacy policies (and probably laws).

**Comment by Mustafax06** [comment]
Thank you for your responses. I'll try that
