### ISSUE TITLE
audio playback occasional gets corrupted after route changes

### ISSUE THREAD

**Issue by harthorst** [AudioKit/AudioKit#2731]
Hi. I'm working on a drum engine app. It uses MIDISampler for playing samples and some mixers, equalizers and a reverb. 
I registered an observer for AVAudioSession.routeChangeNotification so I can reload the samples when the output device changed.

Here is the code for that part:
```
@objc func routeChanged(_ notification: Notification) {
        print("Audio route changed")
        engine.stop()
        loadInstruments()
        try? engine.start()
}
```

On iOS this works well but on MacOS (via catalyst) sometimes the audio does not recover well. It continues playing but after some seconds I get a mono signal or the sound is muted completely. This happens very randomly but after 1-20 route changes I can reproduce the effect.

In the log I see:
```
2022-05-27 21:01:23.210256+0200 compas[17674:5790282]  AudioObjectGetPropertyData: no object with given ID 109
2022-05-27 21:01:23.210337+0200 compas[17674:5790785]  AudioObjectPropertiesChanged: no such object
2022-05-27 21:01:23.210342+0200 compas[17674:5790282] [aqme] AQMEIO_HAL.cpp:463:GetSampleRate: Audio device 109: error 560947818 fetching sample rate, or sample rate is 0. Defaulting to 44100.
2022-05-27 21:01:23.210391+0200 compas[17674:5790282]  AudioObjectGetPropertyData: no object with given ID 109
2022-05-27 21:01:23.361478+0200 compas[17674:5790282] [aqme] AQMEIO.cpp:182:AwaitIOCycle: timed out after 0.150s (1187 1187); suspension count=0 (IOSuspensions: )
2022-05-27 21:01:23.361686+0200 compas[17674:5790369]  AudioObjectGetPropertyData: no object with given ID 109
2022-05-27 21:01:23.361788+0200 compas[17674:5790369]  AudioDeviceStop: no device with given ID
called loadInstruments()
```

Those messages are printed on every route change and it seems there is no correlation to the effect.

Any hints what I can do? This is annoying me since years.

Regards,
Thomas

**Comment by emurray2** [comment]
Was the app working when you didn't handle route changes?

**Comment by emurray2** [comment]
This is something deep down in the Apple code I'm not sure if we would be able to handle. As far as I'm aware, route change notifications are of no use on Mac Catalyst because I have no problem switching outputs without the notifications. Yes, sometimes there is a second or two delay, but I think it's due to how Apple handles their HAL Audio Unit.

Thoughts from anyone else?

**Comment by harthorst** [comment]
> Was the app working when you didn't handle route changes?

Without handling route changes the sequencer stops playing when I select a different output device (in the audio preferences of my mac).

**Comment by emurray2** [comment]
> > Was the app working when you didn't handle route changes?
> 
> Without handling route changes the sequencer stops playing when I select a different output device (in the audio preferences of my mac).

Can you give me some more details below:
- What version of MacOS you're running?
- Are you using M1 or Intel Mac?
- Which branch/version of AudioKit?
- Are you using `AppleSequencer` from AudioKit/AudioKit or `Sequencer` from AudioKit/AudioKitEX?

**Comment by harthorst** [comment]
> Can you give me some more details below:
Sure
> * What version of MacOS you're running?
11.6.4
> * Are you using M1 or Intel Mac?
Intel
> * Which branch/version of AudioKit?
5.0.0 - I think I had similar issues with older versions too
> * Are you using `AppleSequencer` from AudioKit/AudioKit or `Sequencer` from AudioKit/AudioKitEX?
I'm using Sequencer from AudioKit/AudioKitEX

**Comment by harthorst** [comment]
One more thought: Maybe there is a way to reset the complete audio session? I don't need a continuous audio playback - just stability.

**Comment by emurray2** [comment]
> One more thought: Maybe there is a way to reset the complete audio session? I don't need a continuous audio playback - just stability.

You could try `engine.pause()` or `engine.reset()`

**Comment by harthorst** [comment]
thank you for the hint. engine.reset() does not exist in the api and engine.pause() does not have any positive effect

**Comment by emurray2** [comment]
> thank you for the hint. engine.reset() does not exist in the api and engine.pause() does not have any positive effect

My mistake, I meant `engine.mainMixerNode.reset()`, but that probably won't help either. As I mentioned earlier, I speculate the delay being related to how the HAL Audio Unit changes devices, not how the session changes routes.

However, as you mentioned--having the route change notifications is necessary because you can run your code which helps the session run smoother.

My suggestion to help it run smoothly every time would be to pause the sequencer on a route change and have a button which allows the user to resume playback. Otherwise, I'm not sure how to get it to run consistently every time. This seems to be an issue with Apple's code rather than AudioKit's inner workings.

I'll leave this open for now because someone else might have more input, but that's all I can think of.

**Comment by aure** [comment]
I'm not really sure this is something wrong with AudioKit.
