### ISSUE TITLE
Xcode 14 Beta - Swift 5.7 - Can not compile MIDIPlayer

### ISSUE THREAD

**Issue by kvacquier** [AudioKit/AudioKit#2764]
**Demonstrate your bug in a test**

 When trying to compile (using SPM), in Xcode 14 beta 5, latest release of the library (5.4.1), with swift 5.7, got the error :
> Referencing instance method 'makeIterator()' on 'Collection' requires the types 'IndexingIterator<AVAudioSequencer>' and 'IndexingIterator<MIDIPlayer>' be equivalent

Lines : 89, 98, 109,127 of MIDIPlayer.swift

**Comment by bdrelling** [comment]
@kvacquier I have been using Xcode 14 beta exclusively since it doped, with in use almost daily for the projects I work on that all consume AudioKit and several other AudioKit libraries. I haven't run into a single compilation issue. I've also had no issue on Intel or Apple Silicon.

Can you provide more information, such as what platforms you're trying to compile for and any further compilation output?

**Comment by aure** [comment]
Thanks for the heads up but we can't be expected to support beta versions of Xcode or higher than current toolchains.

**Comment by kvacquier** [comment]
I could compile with 5.4.4 so no problem after all

**Comment by James-Knipe** [comment]
> **Demonstrate your bug in a test**
> 
> When trying to compile (using SPM), in Xcode 14 beta 5, latest release of the library (5.4.1), with swift 5.7, got the error :
> 
> > Referencing instance method 'makeIterator()' on 'Collection' requires the types 'IndexingIterator' and 'IndexingIterator' be equivalent
> 
> Lines : 89, 98, 109,127 of MIDIPlayer.swift

Problem persists using Xcode 14.0 beta 6 (14A5294g) with 1 additional line
> Lines : 89, 98, 109, 127, 158 of MIDIPlayer.swift

**Comment by joewoodhouse** [comment]
I'm seeing the same issue on XCode 14.0.1?
