### ISSUE TITLE
Can I play audio in background with AnalogSynthX?

### ISSUE THREAD

**Issue by alejandroluengo** [audiokit/AudioKit#288]
Hi there

Can I play in background? I see that keys in plist are ok but when I touch ADSR to get a very long sound and I go to background AnalogSynthX stops and when it comes back to first plane it continues playing.

Is this a bug or I am missing something?

Best Regards,

**Comment by essej** [comment]
Turns out you need to put this line in the in Conductor's init() before you call AudioKit.start():
  AKSettings.playbackWhileMuted = true
This causes AudioKit to use the proper audio session category to actually keep the engine alive in the background. This should be added as an option in a configuration page in the app, so that it doesn't always just stick around if people don't want it to.

It goes well with the Virtual MIDI port support that was just merged into the develop branch. To use it, you just need to call midi.createVirtualPorts() near the end of Conductor's init().. then other controller apps can connect and play it while it's in the background.

**Comment by aure** [comment]
If anyone wants to add a configuration page for Analog Synth X, we'd happily accept a pull request for that.  Matt and I already have a long list of improvements were making, so help is welcomed.

**Comment by aure** [comment]
After discussing it with @swiftcodex I think it is a good idea to include this as a configuration option, but the default behavior is okay for now.  So, I will close this as a Github issue, but add it to our internal updates list.
