### ISSUE TITLE
Support audio playback on desktop platforms using Miniaudio

### ISSUE THREAD

**Issue by Keithcat1** [AudioKit/AudioKit#2939]
### Description

AudioKit doesn't work on windows. Additionally, getting it working on Windows probably requires interfacing with a bunch of different audio backend / decoding libraries.

### Proposed Solution

[Miniaudio](https://github.com/mackron/miniaudio) is a C library that allows audio playback and recording on Windows, Linux and MacOS. It also comes with WAV, FLAC and MP3 decoders. This might be the easiest way to play audio on Windows.

### Describe Alternatives You've Considered

[Windows runtime media player class](https://learn.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplayer?view=winrt-26100)

**Comment by NickCulbertson** [comment]
To my knowledge there are no plans to port AudioKit to Windows since it is primarily built on Apple's AVFoundation. The closest thing is that the DunneSampler was ported to JUCE which can export cross-platform. I would seek other alternatives for Windows development but the DSP from the effects could be repurposed. The AudioProgrammer's Youtube and Discord has a bunch of resources for JUCE and other frameworks better suited for Windows.
