### ISSUE TITLE
triggerWithEnvelope bug when attack < 0.00001 (10 microseconds)

### ISSUE THREAD

**Issue by Joshua-Thompson** [audiokit/AudioKit#338]
If I use something like...

```swift
import XCPlayground
import AudioKit

var freq = AKOperation.lineSegment(AKOperation.trigger, start: 100, end: 75, duration: 0.5)
var boom = AKOperation.triangleWave(frequency: freq, amplitude: 1.0)
//set attack to 10 microseconds
var boomAttack = boom.triggeredWithEnvelope(AKOperation.trigger, attack: 0.00001, hold: 0.5, release: 0.1)
var gen = AKOperationGenerator(operation: boomAttack)


AudioKit.output = gen
AudioKit.start()
gen.start()

AKPlaygroundLoop(frequency: 1) {
    gen.trigger()
}
XCPlaygroundPage.currentPage.needsIndefiniteExecution = true
````

Then no sound is produced...
If I change attack to 0.0 it works 
If I change attack to 0.0001 (100 microseconds) it also works

is this a bug or just a limitation?

**Comment by aure** [comment]
If it doesn't make a sound, it's a bug.  Great catch.

**Comment by Joshua-Thompson** [comment]
Ok, glad to be off service :)

**Comment by aure** [comment]
I'm going to leave this open until such time as I can investigate it competely.

**Comment by aure** [comment]
This is due to the fact 0.00001 gets printed as "1e-05" which is confusing the Sporth parsing engine.  You won't really heard the difference in attack between these small value, but if you really need tiny numbers for something else, you can game the system with 

`AKOperation(1.0) / 100000`

so that the line would read:

`var boomAttack = boom.triggeredWithEnvelope(AKOperation.trigger, attack: AKOperation(1.0) / 100000, hold: 0.5, release: 0.1)`

There's not much else I can do about with a lot of effort so I'm going to close the issue for now. Perhaps Paul will support scientific notation for numbers in Sporth someday.
