### ISSUE TITLE
AKAudioRecorder: How to record a specific node?

### ISSUE THREAD

**Issue by blerchy** [audiokit/AudioKit#357]
Hi there, I was wondering how I can get an `AKAudioRecorder` to, y'know, actually record something. `AKAudioRecorder`'s interface seems very simple, with only `init(:)`, `record()`, and `stop()`; but I need to know how to get it to record a specific node.

**Comment by aure** [comment]
AKAudioRecorder only records what is coming out of the speaker, ie. the final output.  So, if you wanted to record a specific node, you'd have to install a tap on that node and then write the incoming buffers to disk. I agree it would be really cool if AKAudioRecorder could be given an optional node to record from.

**Comment by arsone** [comment]
This could actually be a huge feature request. Excited about the possibility of doing multitrack recording with audiokit, particularly if an AKAudioRecorder can be attached to each node (or even custom group of nodes).

**Comment by blerchy** [comment]
@aure: Ok, this makes sense. I am, however, having an issue that `AKAudioRecorder` is recording _nothing_ to a file I give it, even though there is an output to `AudioKit.output()`. Is there any sample code or project that you know of which uses `AKAudioRecorder`? Maybe I'm just missing something.

**Comment by aure** [comment]
@blerchy I am wrong about the AKAudioRecorder.  It does not record the output.  It only records the input.  So, I can tackle this problem in two steps.  First, record from the output node, then make a recorder attached to any node.

**Comment by blerchy** [comment]
@aure I am a bit confused now, which input does the `AKAudioRecorder` record from? If I can't get it to record a specific node, can I get it to record from the microphone instead?

**Comment by aure** [comment]
Currently AKAudioRecorder just records from the inputNode, ie. the microphone.  I am working on a node recorder right now.

**Comment by aure** [comment]
@blerchy @arsone In the develop branch, I have committed a new AKAudioRecorder that seems to work like it should.  It defaults to recording the overall AudioKit output (like I thought it was already), but you can also initialize it with a node: so that you can tell it to record from the microphone, or any AKNode.  It seems to only record in .caf format right now and its probably brittle if you try recording the same node (why you would do that I don't know!), but it should suffice for now.  I'll make some playgrounds and examples that use it.  Definitely use with caution!  To use it, either update to the develop branch or just overwrite your AKAudioRecorder.swift contents with the following:

https://github.com/audiokit/AudioKit/blob/ca0cf66af9953741cf1516e12508261892eb93cf/AudioKit/Common/Internals/AKAudioRecorder.swift

I'll leave this issue open while we discuss things, but I will tag it as fixed for now.
