### ISSUE TITLE
AKOperationEffect not working

### ISSUE THREAD

**Issue by ukelady** [audiokit/AudioKit#460]
Hi,

I am trying to let the left and right channels having different different delay unit. This is what I do: 

```
var testWave = AKOperationGenerator(operation: AKOperation.sineWave(frequency: 440, amplitude: 0.4))

var delayLeft = AKOperation.input.delay(time: 0.23, feedback: 0.49)
var delayRight = AKOperation.input.delay(time: 0.2, feedback: 0.49)

var delayed = AKOperationEffect(testWave, left: delayLeft, right: delayRight)

AudioKit.output = delayed
testWave.start()
AudioKit.start()
```

But there is no sound coming out. I wonder if the AKOperationEffect is not working properly or if I've done something wrong. Thanks!

**Comment by aure** [comment]
Fixed in the develop branch: https://github.com/audiokit/AudioKit/commit/73c5aec2944adcc6a75517f117a570741899ea96

Also added leftInput and rightInput in case you're processing incoming stereo.

Here's a playground that shows it working.

Thanks for finding this!

var lfo = AKOperation.sineWave(frequency: 1)
var sine = AKOperation.sineWave(frequency: lfo * 440, amplitude: 0.3)

var sine2 = AKOperation.sineWave(frequency: lfo * 660, amplitude: 0.3)
var testWave = AKOperationGenerator(left: sine, right: sine2)

var delayLeft = AKOperation.leftInput.delay(time: 0.23, feedback: 0.49)
var delayRight = AKOperation.rightInput.delay(time: 0.2, feedback: 0.69)

var delayed = AKOperationEffect(testWave, left: delayLeft, right: delayRight)

AudioKit.output = delayed
testWave.start()
AudioKit.start()
