### ISSUE TITLE
AKAudioPlayer.playFrom performance issue

### ISSUE THREAD

**Issue by andreamazz** [audiokit/AudioKit#472]
Hello everybody.
I'm currently using the `develop` branch, and I noticed a significant performance dip when calling the `playFrom` func of `AKAudioPlayer`.
As you can see here:
<img width="793" alt="screen shot 2016-07-13 at 18 43 10" src="https://cloud.githubusercontent.com/assets/570797/16811711/f4803d84-4929-11e6-903d-373b329423fc.png">
it takes more than a second to respond (I'm testing on an iPhone 6), and each spike corresponds to a call to `playFrom`.

The highlighted method in the stack simply calls `playFrom` passing as parameter the player's playhead minus 5 seconds.

Here's the detailed stack of calls:
<img width="1011" alt="screen shot 2016-07-13 at 18 43 28" src="https://cloud.githubusercontent.com/assets/570797/16811818/72c40086-492a-11e6-9d5d-50e90fcb0b76.png">

If I switch back to the `master` branch the performances go back to normal (the same method call is basically instantaneous).

Let me know if you need further info.

**Comment by aure** [comment]
Thanks for this, will investigate.

**Comment by laurentVeliscek** [comment]
Hi !

What file are you playing ? Is it an mp3 file ? That could explain why you get such a long time as audioplayer needs to feed its buffer, and it takes much longer time with mp3 / mp4 or any compressed format (it costs an expensive "uncompress" time...). With a long mp3, it is a problem. But if you convert to PCM format (no compression), you should get a much better performance (I hope).

The way develop branch's AKAudioPlayer works is very different from master's version.

Without entering into details, develop uses scheduleBuffer when master uses scheduleSegment.
Both have their advantages and their limitations. As we cannot predict if looping or playfrom will be used instead of just playing the file, I choosed to use the "scheduleBuffer" as it was the only option to have a working AKAudioPlayer with those features. (You may have noticed some bugs with master's version).

If you have any idea to optimize the actual develop version, you're very welcome.  May be we could add another player, with another approach for different purposes.

But please try with a PCM file and let us know if the performance is still unacceptable.

Best,

Laurent.

**Comment by andreamazz** [comment]
Hi @laurentVeliscek and @aure 
Thanks for the quick reply. 
I'm currently using m4a files (I did notice that mp3 files take even longer). 
I'll follow your suggestion and decode them in a PCM file before feeding them to the player. I'll let you know how it ends up.

In the meantime thanks again for all your work. 👍 
Cheers

**Comment by laurentVeliscek** [comment]
I just experimented with a 3 minutes mp3 file in playground. It works not so bad, but it's in playground... Must test on hardware. I suggest to not use "playFrom()" but just set player!.startTime. (check audioPlayer playground code). If the file is already playing, it will move the playhead, and play just like playFrom() does. Not sure it will work better, but worth to be tested...

Let us know !

Best !

Laurent.

**Comment by laurentVeliscek** [comment]
Could you please post your code ? Would like to check something...

Thanks :-)

Laurent.

Envoyé de mon iPhone

**Comment by andreamazz** [comment]
Sure. As I said I'm importing a song from the library and convert it in m4a format:

```swift
  func exporterFor(asset: AVAsset, at exportedFileURL: NSURL) -> AVAssetExportSession {
    // Export as a .m4a file preset
    let exporter = AVAssetExportSession(asset: asset, presetName: AVAssetExportPresetAppleM4A)!
    exporter.outputFileType = AVFileTypeAppleM4A
    exporter.outputURL = exportedFileURL

    // Set the length of the export to be the length of the song
    let duration = CMTimeGetSeconds(asset.duration)
    let endTime = Int64(duration)
    let startTime = CMTimeMake(0, 1)
    let stopTime = CMTimeMake(endTime, 1)
    let exportTimeRange = CMTimeRangeFromTimeToTime(startTime, stopTime)
    exporter.timeRange = exportTimeRange

    return exporter
  }

  func exportFromAppleMusic(chosenSong: MPMediaItem, completion: (Result<Song, NSError> -> Void)) {
    // Set up the export
    let filename = "\(chosenSong.persistentID).m4a"
    let documentsDirectory = NSFileManager.defaultManager().URLsForDirectory(.DocumentDirectory, inDomains: .UserDomainMask)[0]
    let exportedFileURL = documentsDirectory.URLByAppendingPathComponent(filename)

    // Set up the export
    let url = chosenSong.valueForProperty(MPMediaItemPropertyAssetURL) as! NSURL
    let songAsset = AVAsset(URL: url)

    let exporter = exporterFor(songAsset, at: exportedFileURL)
    exporter.exportAsynchronouslyWithCompletionHandler({
      switch exporter.status {
      case .Completed:

        /// ... (skipping the part where I save the metadata in a Realm database)

        Async.main {
          completion(.Success(song)) // Song is the model object with the file URL
        }

        break
      default:
        print("Export status \(exporter.status) error: \(exporter.error)")
        completion(.Failure(exporter.error ?? NSError(domain: "tunedown", code: 0, userInfo: nil)))
      }
    })
  }
```

Then I play the imported song like this:
```swift
  func playSong(songToPlay: NSURL) {
    let file = try! AKAudioFile(readFileName: songToPlay.pathComponents!.last!, baseDir: .Documents)
    player = try! AKAudioPlayer(file: file)

    timePitch = AKTimePitch(player!)

    AudioKit.output = timePitch
    AudioKit.start()

    player?.play()
  }
```

And I skip back with this:
```swift
  @IBAction func jumpBack() {
    guard let player = player where AudioKit.engine.running else { return }

    var starting = player.playhead - 5
    if starting < 0 {
      starting = 0
    }
    player.playFrom(starting)
  }
```

**Comment by laurentVeliscek** [comment]
Ole !
(Amazing !)

Would you like to add a method to AKAudioFile so it could  import from library ?
(That would be cool...) 

AKAudioFile.export() couldn't convert from compressed file to uncompressed format.
(because it relies on AVAssetExport)

But since latest methods exist (normalize, extract...), it's now possible.

With Brandon, we're almost done in implementing async methods for extracting some audio and convert it in .caf un-compressed format. So we have a piece of the puzzle. You've got the other.

I hope to  publish  and commit extract_async() for AKAudioFile tomorrow. It lets you convert any readable file to uncompressed .caf AKAudioFile (the most suitable format for efficient process).

Then, if you implement a convenient init (fromMPMediaItem) for AKAudioFile, we could complete the puzzle.

I planned to add some new vars to AKAudioFile: .player -> AkaudioPlayer, and .sampler -> AKSampler.

So our Lego box  will begin to be very fun to use...

:-)

By the way, I can't see the purpose of your application... (except for debugging AKAudioPlayer ;-)

Best !

Laurent.

PS: Except for experimentation, **never** use try!, at least try? or better, do {try} catch...
PS2: About jumpBack(), you can set player.startTime" (player.startTime =  value) instead of playFrom().
Should be more efficient...

**Comment by andreamazz** [comment]
> Would you like to add a method to AKAudioFile so it could import from library ?
> (That would be cool...)

Sure, I'll be happy to.

> With Brandon, we're almost done in implementing async methods for extracting some audio and convert it in .caf un-compressed format. So we have a piece of the puzzle. You've got the other.
> 
> I hope to publish and commit extract_async() for AKAudioFile tomorrow. It lets you convert any readable file to uncompressed .caf AKAudioFile (the most suitable format for efficient process).
> 
> Then, if you implement a convenient init (fromMPMediaItem) for AKAudioFile, we could complete the puzzle.

Sounds good 👍 

> By the way, I can't see the purpose of your application... (except for debugging AKAudioPlayer ;-)

:D 
I'm a guitarist, so I wanted to build a simple app to slow down and change the pitch of a song, which helps me transcribing it.

> PS: Except for experimentation, never use try!, at least try? or better, do {try} catch...

Yep, I usually avoid any kind of `!` (either forced unwrap or try!), but while I'm still figuring everything out I tend to cut some corners.

> PS2: About jumpBack(), you can set player.startTime" (player.startTime = value) instead of playFrom().
> Should be more efficient...

WIll do, thanks!

Cheers

**Comment by aure** [comment]
Hmm, so is this still an issue?  If not, please don't forget to close it, thanks.

**Comment by andreamazz** [comment]
Ok, I just tested the code by converting the file to PCM, and it works great. 👍
