### ISSUE TITLE
AKAudioFile enhancement

### ISSUE THREAD

**Issue by Ferrick90** [audiokit/AudioKit#509]
Hi,

I would like to change the file created format from .caf change to .m4a format. Hope in future can add more fileExtensionFormat parameter in AKAudioFile(writeIn: .Temp, name: fileName) become AKAudioFile(writeIn: .Temp, name: fileName, ext: .m4a). It will be easy for everyone.

Regards,
Ferrick Chan

**Comment by laurentVeliscek** [comment]
Hi!

You're welcome to add any improvement to AKaudioFile.

About file formats, you must be aware of some consequences of changing convenience  write init.

As AKaudioFile inherits from avaudiofile, you can always create any format AKaudioFile if you wish, using standard inherited inits :
    public override init(forWriting fileURL: NSURL,
                                    settings: [String : AnyObject],
                                    commonFormat format: AVAudioCommonFormat,
                                                 interleaved: Bool) throws {

But for example, creating a m4a as you suggest means you have to set compression settings at least, and may be sample rate. But at the end you may reinvent a wheel:
Except the directory setting, you would mimic the super class init. 

Then, you should probably have to rewrite aknoderecorder, and most of AKaudioFile process convert and peripherals helpers would may be need to be rewritten as well. For example, you cannot export a m4a to wav using avexport (it won't work). And recording to a wav files seems to generate bad formatted files (wav files with a wrong header)

The reason I choosed .caf instead of wav, for example, is because there's an issue with .wav files that seem to be forced to be non float when you init then using avaudiofile init.

The idea behind AKaudioFile was to keep things as simple as they can be in most audiofile uses. Just use the default way ensures that it will work, with less code.
(It is the major benefit of using AKaudioFile instead of avaudiofile)

You can record a m4a file, but it will use some cpu to encode file, so it is a better option to use pcm encoded files to avoid some cpu hog with an heavy real time process chain.

Using m4a format for playing will slow player's responsiveness.
(Because audio decompression take some significant time with longer files)

Compressed files must be converted to pcm prior to any file processing.
So even if the data is compressed on disk, there's no real benefit.
M4a is only relevant for file distribution, but not working.

So, forcing to create .caf was a deliberate option.

The process I encourage is to create and record a pcm (uncompressed)  file set to match audioKit settings. Then make any process you want, and finally export to m4a if you need.

AKaudioFile does this automatically, behind the scene, so you don't have to take care of how it is done. It's easy and efficient. 

You still have the choice to pick another path, using nsurl inits.
But in very most cases, the best choice will be to use the default behavior,
It will work and avoid multiple decode encode passes.

I just wanted to explain why AKaudioFile has been implemented like this. And I must say I really enjoy coding a working recorder or a sampler with a very few code lines number. It is easy and fast.

But I may be wrong.  And may be a m4a init is really needed.

For me. the init is not a priority for improvements.
It works fine.

But for example, the way normalize or extract methods has been coded is far to be optimized as it could be. And I thought about implementing offline processing using an audioKit signal chain that would be very cool. (Aurelius gave a clue to achieve this using aktest that computes a number of samples and is not real time)





Envoyé de mon iPhone

**Comment by laurentVeliscek** [comment]
Sorry, my previous mail has been sent too early (I use my iPhone :-/

To conclude, 
I just wanted to thank you for your interest on AKaudioFile. My goal is to avoid any waste of time and work (but may be I'm wrong, let's debate !), and suggest some other tracks for AKaudioFile improvements.

Best !

Laurent Veliscek.

Envoyé de mon iPhone

**Comment by Ferrick90** [comment]
Hi Laurent,

I see. Thanks to explain to me. The reason why I need to create m4a instead of caf because Android couldn't support caf format. At the moment, I must convert the format before upload to server side. It duplicated the step for me.

Between, AudioKit is the most best library for audio. I used a lot of audio library or tried written by myself. AudioKit have provided full facilities. I like the features, coding style and structure.

In future, I will try to PR to enhance AudioKit become more flexible to let the developers to achieve them goals.

Thanks.

Regards,
Ferrick Chan
