### ISSUE TITLE
Carthage for XCode-beta 8

### ISSUE THREAD

**Issue by terenzeyuen** [audiokit/AudioKit#511]
Tried this on latest XCode Beta but getting "module file was created by an older version of the compiler'...

**Comment by megastep** [comment]
This is normal behavior is you are using the Xcode 8 beta. The binaries were built with Xcode 7 so they can actually be used in submitted applications to the App Store currently.

We'll have these once Xcode 8 is out of beta, in the meantime you'll have to compile it yourself from source.

**Comment by gargantuan** [comment]
Is it currently possible to compile with Xcode-beta 8? I'm new to Xcode so forgive my *noobness*, but when I open the source projects, Xcode-beta is unable to build it due to errors. Is there someway to configure Xcode-beta 8 to compile AudioKit, or is it just not possible at the moment?

I've also tried the `Xcode8-Swift3` branch but it looks like that branch isn't ready for public consumption yet.

**Comment by aure** [comment]
We haven't made the switch to Xcode8 yet, perhaps next week.

**Comment by aure** [comment]
@gargantuan There's now an Xcode8-Swift2.3 branch that works on Xcode8 for me.
