### ISSUE TITLE
error cannot readIntBuffer, Error: Error 

### ISSUE THREAD

**Issue by estock** [audiokit/AudioKit#606]
Trying to add silence to the beginning of a recorded audiofile

```
                    let silence = try! AKAudioFile.silent(samples: 88100)
                    print("silence",silence.duration)
                    
                    let fullLoop = try! silence.appendedBy(file: player!.audioFile)
                    print("fullLoop",fullLoop.duration)
            
                    try! player?.replaceFile(fullLoop)
                    
                    do {
                        try player?.reloadFile()
                    } catch { print("Errored reloading.") }
```
both the silence and the players audio file seem to exist and have the right duration but when I try to append them I get the error 

`error cannot readIntBuffer, Error: Error Domain=Foundation._GenericObjCError Code=0 "(null)"`

**Comment by aure** [comment]
I'm looking into this, didn't want you to think this was being ignored.

**Comment by aure** [comment]
I got this to work using a reference to the audio file directly instead of referring to the player's audiofile.  When I did it your way I got your error plus a little more information:

error cannot readIntBuffer, Error: Error Domain=Foundation._GenericObjCError Code=0 "(null)"
WARNING AKAudioFile.append: appended file should be of same format as source file!
WARNING AKAudioFile.append: trying to fix by converting files...
AKAudioFile.append: source file has been successfully converted
fatal error: Array index out of range

So, if possible, try to access the audio file directly.

HTH

**Comment by laurentVeliscek** [comment]
Did you check that the number of channels of the appended file match with the source file ?

The error message seems to give us a clue...
(Hope this will help to figure out where the problem comes from. The "index out of range" may come from appending mono and stereo files...)

Best

Laurent.

Envoyé de mon iPhone

**Comment by aure** [comment]
Okay, here's something amazing, and a major clue.  The Recorder Demo works perfectly on my iPad Pro, but does not record on my iPhone 7+.  WTF

**Comment by aure** [comment]
Holy moly, it works once you remove the lightning cable from the phone!  Try that after you install it, just disconnect it from your computer and rerun the recorder.

**Comment by aure** [comment]
I think it might be because the iPhone 7 has no headphone port, and the lightning cable being plugged in is making it think that is the primary sound device.

**Comment by aure** [comment]
Sorry all these messages were posted to the wrong issue.

**Comment by aure** [comment]
I'm going to assume this is resolved, but please reopen if not.
