### ISSUE TITLE
Center frequency in AKEqualizerFilter and AKPeakingParametricEqualizerFilter

### ISSUE THREAD

**Issue by isaacengel** [audiokit/AudioKit#722]
For some reason, I am getting a center frequency exactly double the one I set. E.g: if I set the center frequency to 1kHz, the peak/notch appears at 2kHz.
I have tried different filter implementations. This issue happens with AKEqualizerFilter and AKPeakingParametricEqualizerFilter. It does not happen with AKParametricEQ.

**Comment by aure** [comment]
Very interesting.  I'll take a look today.

**Comment by aure** [comment]
I would be surprised if AKHighShelfParametricEqualizerFilter isn't also affected.

**Comment by aure** [comment]
You've found a nasty, pervasive bug, we'll fix this and get a new release out asap!

**Comment by aure** [comment]
So, the bug you found touches most of the effects in AudioKit.  I was using a single mono effect on both channels, so you noticed a doubling of the frequency.  Now I use two effects for everything.  It will increase memory usage but it shouldn't affect the CPU performance.  Overall, it was a great catch.  The fix is on the develop branch, but we'll make a release soon.

**Comment by aure** [comment]
Updated in AudioKit 3.5.2, just released. Thanks again.

**Comment by isaacengel** [comment]
Glad to help!
