### ISSUE TITLE
Q factor in AKParametricEQ

### ISSUE THREAD

**Issue by isaacengel** [audiokit/AudioKit#723]
I am trying to implement a filter with AKParametricEQ and it seems that I am getting a Q factor smaller than the one I am setting.
For example, I set: gain = -20 dB, center frequency = 2000 Hz, Q = 4. Then, I would expect to get a notch centered in 2 kHz with a bandwidth of 2000/4=500 Hz. However, I am getting a bandwidth of 4300 Hz (that is, Q=2000/4300=0.47). See graph attached.
I tried the same parameters in AKEqualizerFilter and AKPeakingParametricEqualizerFilter and I get the expected (correct) results.
![image](https://cloud.githubusercontent.com/assets/25273291/22555506/d31cc05e-e95b-11e6-81d7-3be43ec9a7da.png)

**Comment by aure** [comment]
You're really a godsend putting these filters through their paces.  This particular one is troublesome because it is merely a wrapper for Apple's parametric EQ and we have less control at the DSP level.  However, if you give me a few more data points (at least one more if things are linear) of parameters you gave and what you got vs. what you were expecting, I could probably reverse Apple's mistakes.  It's a bit of a hack, but worth it to make it right.

**Comment by isaacengel** [comment]
Well, I got a couple more for you. I hope this helps!
In the first one, parameters that I set: G=-20dB, f0=2kHz, Q=8.
I would expect cutoff frequencies in: f1=1878.902Hz, f2=2128.902Hz (bandwidth = 250 Hz).
Results I get (see image): G=-20dB, f0=2kHz, f1=1150Hz, f2=3482Hz.
That is bandwidth=2332Hz and Q=0.858.
![image](https://cloud.githubusercontent.com/assets/25273291/22589133/a251e9b8-ea00-11e6-9cdb-4653fd855e8b.png)

Second one, parameters I set: G=-20dB, f0=2kHz, Q=12.
Expecting BW=166.667Hz, f1=1918.402Hz, f2=2085.069Hz.
Results I get (see image): G=-20dB, f0=2kHz, f1=1459Hz, f2=2722Hz.
That is bandwidth=1263Hz and Q=1.584
![image](https://cloud.githubusercontent.com/assets/25273291/22589701/80cf6150-ea03-11e6-9dd1-3f42ca72185a.png)

**Comment by aure** [comment]
Well, so it seems like the Q you are getting is about 8.5x smaller than the Q you want.  since Q is limited in range by Apple from 0.1 to 20, this is means the effective range is more like 0.01->2.4.  

This is literally all the documentation Apple provides for this:

```
// Global, Hz, 0.1->20, 1.0
public var kParametricEQParam_Q: AudioUnitParameterID { get }
```

Given that Apple's band filter is totally hosed in iOS10 (I think that's when it broke), I'm not sure how much we should rely on their filters.  

About all I could do for you is provide a scaling of 8.5, but that seems really lame.  I'm about ready to ditch this filter and the band pass filter. What do you think?

**Comment by isaacengel** [comment]
I agree that patching it by scaling the Q is not the cleanest solution. I don't think we can even tell if the variation in Q is exactly linear.
I have not tried the band pass one, but in the case of the parametric EQ filter, I wouldn't miss it if you ditched it, knowing that other options like AKEqualizerFilter have the exact same purpose and work just right. I don't speak for other AudioKit users, though!

**Comment by aure** [comment]
Thank you again for your critical ear.
