### ISSUE TITLE
FFT buffer is halved before being exposed to user

### ISSUE THREAD

**Issue by dsherret** [audiokit/AudioKit#724]
First of all, thanks for creating this project!

I'm very new to FFTs, but I believe it's required to know the buffer size to get what frequency corresponds with what index (http://stackoverflow.com/questions/4364823/how-do-i-obtain-the-frequencies-of-each-value-in-an-fft).

With that in mind, the fft data returned is halved in [AKFFTTap.swift](https://github.com/audiokit/AudioKit/blob/3044f4b3fa45a2ee64eb9c6a40c533b0df606065/AudioKit/Common/Taps/AKFFTTap.swift). The buffer size is 1024, but the fftData size exposed to the user is 512. The reason why this was done is outlined in #658.

I think this could cause someone to falsely believe the buffer size is 512. What do you think?

**Comment by PaulBatchelor** [comment]
This is actually pretty typical for FFTs. When you apply an FFT to a real signal (an audio signal is a real signal), the FFT is symmetrical, so you toss out that data. 

Because it seems to be only returning floating point values, the thing I'd be curious about is if the FFT routine is providing just the real values or a magnitude spectrum. It doesn't seem like you would be able to access the imaginary components.

**Comment by PaulBatchelor** [comment]
Did some more quick digging:

https://github.com/audiokit/AudioKit/blob/3044f4b3fa45a2ee64eb9c6a40c533b0df606065/AudioKit/Common/Internals/EZAudio/EZAudioFFT.m#L169

I'm going to guess based on this line that it is returning the magnitude spectrum, which would only be from 0 to N/2, or half the input buffer size. A little bit confusing if you aren't familiar with the math behind it, but very typical.

**Comment by aure** [comment]
I think this is a common implementation so I'm going to opt to leave it.  Feel free to reopen this issue if you want to continue the discussion.
