### ISSUE TITLE
sh file inside framework causes error when publishin code to app store

### ISSUE THREAD

**Issue by cenkingunlugu** [audiokit/AudioKit#747]
When i try to upload my code to App Store, It gave a strange error like "your files are not signed with a valid distribution profile"

When i checked files in my app i saw this file:

    ./Pods/AudioKit/iOS/AudioKit.framework/fix-framework.sh

After i did:

    rm ./Pods/AudioKit/iOS/AudioKit.framework/fix-framework.sh

I could publish my app. But it stole my 3 hours.

For other users for not having the same problem. please remove that file from the framework. It seems that the right place for that file is not there.

Thanks.

**Comment by megastep** [comment]
Wow, that must be a recent change on the Apple servers being less intolerant of other data files within the framework. I'm pretty sure this was not happening before. That said, you typically need to run that script before submitting. Maybe we should add some commands to automatically purge itself from the build.

**Comment by megastep** [comment]
I'm surprised about this as I just submitted an app using AudioKit (from CocoaPods) to Apple and didn't get any such errors with the framework.

**Comment by cenkingunlugu** [comment]
Was it a new project written in swift? Was it built with latest stable xcode? Did you use Archive & then use Upload To App Store button inside organizer?

All of these were yes for me.

Maybe there can be a difference with your and my builds.

**Comment by cenkingunlugu** [comment]
look at this: http://stackoverflow.com/a/29905611/256201

and see 5

**Comment by megastep** [comment]
I always build with the latest official Xcode and use the regular archive and upload. The only difference here is that my app is actually in Objective-C, but really this shouldn't make a difference since the error your get is about the framework itself.

I think your problem might just be that you are not actually running the fix-framework.sh script in a run phase in your project. It should clean itself out of the final build if you do.

You need to call this as part of your build:

`"$BUILT_PRODUCTS_DIR/$FRAMEWORKS_FOLDER_PATH/AudioKit.framework/fix-framework.sh"`

**Comment by cenkingunlugu** [comment]
i think doing it manually is a problem. you can remove it on post install of your pod.

would you like me to fix it and make a pull req?

**Comment by megastep** [comment]
If you can make the pod version easier to use, feel free. :)
It's not just the removal though, the script itself does other things and should be called as a matter of course.

**Comment by megastep** [comment]
Let me clarify that the right time to remove the script is not after it got installed from the pod, but rather after it has been run by your target as part of your build process. It only gets removed from the final build product but must stay a part of your build chain. Otherwise you're going to run into a host of other issues when submitting binaries to Apple.

**Comment by cenkingunlugu** [comment]
A-ha i got the point.

https://github.com/audiokit/AudioKit/blob/f45c4c21d34d0c986a134f2720e55def366fc248/Frameworks/INSTALL.md#handling-bitcode

here you say that

for me it was not clear what that bitcode checkbox needed for and it was coming checked, and i did not read this before. as it was coming checked, i did not uncheck it and i think my problem was coming from here.

i think it is a problem of apple that it comes checked when you try to publish and it is a problem for audiokit that who uses this framework and does not care (or know) what bitcode means and why it is important will fail on publishing it if they did not read the Install.MD

If you feel it is clear that user have to read Install.MD fully, you can close this issue.

**Comment by megastep** [comment]
Yeah, I think we can definitely improve on the clarity of some of these instructions. Bitcode has become more ubiquitous these days, so in practice you really want to be calling that script every time now...

**Comment by shanminxu** [comment]
just remove first line: 
#!/bin/bash
and it works.

**Comment by megastep** [comment]
If you run the script properly in your project in a run phase, it should remove itself from the final build and this won't be a problem.
