### ISSUE TITLE
EXC_BAD_ACCESS initializing AKMorphingOscillatorBank

### ISSUE THREAD

**Issue by paulmasson** [audiokit/AudioKit#768]
Using the framework version 3.5.3, I'm getting a runtime crash in `sp_oscmorph_init` with these lines of code:

     var bank = AKMorphingOscillatorBank(waveformArray:[ AKTable(.sine), AKTable(.triangle) ])
     AudioKit.output = bank
     AudioKit.start()   
     bank.play(noteNumber: 36, velocity: 80)

Things are working fine with AKOscillatorBank when specifying a single waveform, so I'm at a loss as to what's wrong. If I'm missing something simple, please let me know. Thanks!

**Comment by aure** [comment]
I'm updating the docs, but the problem is that you need to give it exactly four waveforms in that array.  If you only need two, just put blank AKTables in the other slots, or do sine, triangle, sine, triangle.  Making it an arbitrary size array is definitely too difficult, but perhaps a two table version makes sense.  I don't think you'll suffer too much of a hit to double up the waveforms though.
