### ISSUE TITLE
AKAudioFile Export Fails

### ISSUE THREAD

**Issue by dkun7944** [audiokit/AudioKit#792]
I've been trying to record and save audio files in my app, but have been getting errors like this:

`Export Failed Optional(Error Domain=NSURLErrorDomain Code=-1 "unknown error" UserInfo={NSLocalizedDescription=unknown error, NSErrorFailingURLStringKey=/private/var/mobile/Containers/Data/Application/AA50830D-157C-4940-BBB5-2003D9B1A586/tmp/D44BFA64-D3BF-4166-9A16-8C3D8A04E49C.caf, NSErrorFailingURLKey=/private/var/mobile/Containers/Data/Application/AA50830D-157C-4940-BBB5-2003D9B1A586/tmp/D44BFA64-D3BF-4166-9A16-8C3D8A04E49C.caf, NSURL=/private/var/mobile/Containers/Data/Application/AA50830D-157C-4940-BBB5-2003D9B1A586/tmp/D44BFA64-D3BF-4166-9A16-8C3D8A04E49C.caf, NSUnderlyingError=0x17004edc0 {Error Domain=NSOSStatusErrorDomain Code=-12935 "(null)"}})`

I thought it might be something I'm doing wrong with my own app, so I tried building RecorderDemo. It works perfectly if you use ./build_frameworks.sh and include AudioKit as an embedded framework. But if you use cocoapods instead without changing anything else, the error above occurs.

It seems like there's been a lot of recording/saving issues recently, so maybe this can point us in the right direction to get this resolved.

**Comment by aure** [comment]
yeah, this is probably related to https://github.com/audiokit/AudioKit/issues/754 but we can keep both issues open until its resolved.  Interesting that Cocoapods behaves differently.  Are you on the master branch?  There have been a few pull requests to master that its possible that its more up to date than Cocoapods.  We should probably make a release soon to see if that at least normalizes things.

**Comment by dkun7944** [comment]
Not entirely sure where cocoapods is pulling from, but I know it's on 3.5.3.

**Comment by gazebofire** [comment]
I'm also seeing a similar issue with a variation of the RecorderDemo exercise file. Also using Cocoapods with 3.5.3.

`deleteFileWithFileName "79F0E6E7-DD78-450B-8E7F-4550FEEFC362.caf" deleted.
cleanTempDirectory() 1 files deleted
initialize() AKAudioPlayer Warning:  "6096A844-A3AB-4A79-8C32-927FA0EFA247.caf" is an empty file
record() AKNodeRecorder: recording
record() AKNodeRecorder writing (file duration: 0.1 seconds)
record() AKNodeRecorder writing (file duration: 0.2 seconds)
record() AKNodeRecorder writing (file duration: 0.3 seconds)
record() AKNodeRecorder writing (file duration: 0.4 seconds)
record() AKNodeRecorder writing (file duration: 0.5 seconds)
record() AKNodeRecorder writing (file duration: 0.6 seconds)
record() AKNodeRecorder writing (file duration: 0.7 seconds)
record() AKNodeRecorder writing (file duration: 0.8 seconds)
record() AKNodeRecorder writing (file duration: 0.9 seconds)
record() AKNodeRecorder writing (file duration: 1.0 seconds)
record() AKNodeRecorder writing (file duration: 1.1 seconds)
stop() AKNodeRecorder: Recording Stopped.
exportAsynchronously(name:baseDir:exportFormat:fromSample:toSample:callback:) internalExportSession session created
queueExportSession(session:) ExportFactory: exporting session #0
Export failed: Optional(Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={NSLocalizedFailureReason=An unknown error occurred (-12936), NSLocalizedDescription=The operation could not be completed, NSURL=/tmp/6096A844-A3AB-4A79-8C32-927FA0EFA247.caf, NSUnderlyingError=0x60800005c3b0 {Error Domain=NSOSStatusErrorDomain Code=-12936 "(null)"}})
completionHandler() ExportFactory: session #0 Completed
completionHandler() ExportFactory: All exports have been completed
2017-03-27 18:38:34.847 Sampler[96192:1527313] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'player started when in a disconnected state'`

**Comment by dkun7944** [comment]
@gazebofire 'player started when in a disconnected state' usually means your AudioKit's output is not set to the player node. You should probably use an AKMixer to connect the recorder and player nodes and then set AudioKit.output to be the mixer.
