### ISSUE TITLE
Crash when following mic playground example

### ISSUE THREAD

**Issue by zmcartor** [audiokit/AudioKit#843]
This is my view controller. Code was taken from AudioKit playground example regarding visualizing output from a mic. 

```
class SecondLesson: UIViewController {

    @IBOutlet var visualView: UIView!
    var tracker:AKFrequencyTracker?
    var silence:AKBooster?
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        AKSettings.audioInputEnabled = true
        let mic = AKMicrophone()
        
        AVAudioSession.sharedInstance().requestRecordPermission { (allowed: Bool) in
         
            if allowed {
                if let inputs = AudioKit.availableInputs {
                    try! AudioKit.setInputDevice(inputs[0])
                    try! mic.setDevice(inputs[0])
                }
                
                self.tracker = AKFrequencyTracker(mic, hopSize: 200, peakCount: 2_000)
                self.silence = AKBooster(self.tracker, gain: 0)
                AudioKit.output = self.silence
                AudioKit.start()
        }
    }
    
    }

    override func viewWillDisappear(_ animated: Bool) {
        AudioKit.stop()
        AudioKit.output = nil
    }
}
```

Crash log shows:

```
2017-04-07 13:51:05.836 FillyFilter[9576:773934] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: !nodeMixerConns.empty() && !hasDirectConnToIONode'

```

I've searched the mailnglist, and cannot find a solution. From the playground, this example should work, right ? 

Thanks very much for looking.

**Comment by aure** [comment]
I think you'll nmeed to move the mic up out of local declaration in viewWIllAppear.  

This is discussed in the new "Playgrounds To Production" playground inside the Basics playground.
https://github.com/audiokit/AudioKit/blob/master/Playgrounds/AudioKitPlaygrounds/Playgrounds/Basics.playground/Pages/Playgrounds%20to%20Production.xcplaygroundpage/Contents.swift

Also, its bad practice to put AudioKit in view controller life cycle.  It could easily get called twice, things like that.  Actually I think its possibly worse because you're doing AudioKit stuff within a block.  

I don't think you're far off, but too many variables to say for sure exactly what's the cause.  Keep plugging with these suggestions.  

In general I don't think this is an AudioKit issue, more of a discussion forum topic, maybe post there next?

Thanks!

**Comment by zmcartor** [comment]
Sorry, and thanks very much for the suggestions! I didn't see the new "Playgrounds To Production" docs :D 👍
