### ISSUE TITLE
Possible to simplify installation instructions

### ISSUE THREAD

**Issue by hhanesand** [audiokit/AudioKit#859]
In `INSTALL.md` the following instructions are given :

1. Drag and drop the AudioKit For {platform}.xcodeproj file to your project in Xcode. The file is located within the AudioKit/{platform} subdirectory in the repository, where {platform} is one of iOS, macOS or tvOS.
2. Go to the project settings for the target of your project using AudioKit, go to the Build Phases tab, and expand the Target Dependencies to add a dependency on the AudioKit target.
3. In the Link Binary With Libraries section, make sure to add the AudioKit.framework dependency.
4. In the General tab, also add AudioKit.framework in Embedded Binaries.

At least on iOS, adding AudioKit.framework to Embedded Binaries automatically performs steps 2 and 3.

**Comment by megastep** [comment]
That must be new then, it certainly wasn't being done automatically by Xcode in previous versions...

**Comment by aure** [comment]
I think the disconnect here is just that those instructions are for using the AudioKit ".xcodeproj" file in your project rather than using the .framework file.  When you use the framework directly, you're right, all you have to do is drag it to embedded binaries. If I am wrong I'll happily reopen the issue and update the docs.  In the second half of this video I do the .xcodeproj stuff:

https://vimeo.com/audiokit/audiokit-framework-issues

**Comment by hhanesand** [comment]
I copied the `AudioKit` folder into my project folder, added the `AudioKit.xcodeproj` to my project in Xcode, and then added the `AudioKit.framework` to the Embedded Binaries, and also automatically did steps 2 and 3.

**Comment by aure** [comment]
I see what you're saying. You're right, that is working.  Do you want to update the docs or should I?
