### ISSUE TITLE
How can I use AudioKit as Noise Gate?

### ISSUE THREAD

**Issue by Adam259532** [AudioKit/AudioKit#963]
It's really wonderful framework.
I saw various dynamics processor functions here, but not yet noise gate.
Don't you have noise remover such as Audacity have?
Now AudioKit has noise generator, but not remover.

**Comment by aure** [comment]
Sorry for the delay in responding.  I guess you could do something where you detect the overall amplitude using the amplitude tracker and set output to zero if the amplitude detected is below a threshold.

**Comment by aure** [comment]
Of course that would be a very basic gate.   You might want to do something slicker where the amplitude from 0-threshold is not completely zero but heavily scaled, so that there's a smoother transition to sound. Perhaps tying low pass filter parameters to the detected amplitude.  I'm sure there's an art to good noise filtering.

**Comment by shadow-jafar** [comment]
> output
You are saying set output to zero
what do you mean by output here? Is it a compressor?
